Repository redis/redis-py, pull requests merged in 2021-12, with the labels that each got.

#1754 Remove unused aggregation subclasses
  redis/commands/search/aggregation.py
Labels: 4.1.0

#1762 Migrated targeted nodes to kwargs in Cluster Mode
  README.md
  redis/client.py
  redis/cluster.py
  redis/commands/__init__.py
  redis/commands/cluster.py
  redis/commands/core.py
  tests/test_cluster.py
  tests/test_commands.py
Labels: chore, breakingchange, 4.1.0

#1683 Integrate RedisBloom support
  redis/commands/bf/__init__.py
  redis/commands/bf/commands.py
  redis/commands/bf/info.py
  redis/commands/redismodules.py
  setup.py
  tests/test_bloom.py
  tox.ini
Labels: feature, 4.1.0

#1735 Aggregation loadall
  redis/commands/search/aggregation.py
  tests/test_search.py
Labels: 4.1.0

#1763 Run actions in Parallel
  .github/workflows/integration.yaml
  tasks.py
Labels: chore

#1770 Fixing lint merge issue
  tests/test_connection_pool.py
Labels: chore

#1756 Added support for MONITOR in clusters
  redis/cluster.py
  tests/conftest.py
  tests/test_cluster.py
  tests/test_commands.py
  tests/test_connection_pool.py
  tests/test_monitor.py
  tests/test_pubsub.py
Labels: chore, 4.1.0

#1774 Fix cluster ACL tests
  tests/test_cluster.py
  tests/test_commands.py
Labels: chore

#1778 Fixing the license link in the readme
  README.md
Labels: chore

#1780 Add packaging to setup_requires, and use >= to play nice to setup.py (fixes #1625)
  setup.py
Labels: chore

#1779 Adding cluster, bloom, and graph docs
  docs/index.rst
  docs/redis_cluster_commands.rst
  docs/redis_commands.rst
  docs/redismodules.rst
  redis/commands/bf/commands.py
  redis/commands/graph/commands.py
Labels: chore

#1787 Disabling JSON.DEBUG tests
  tests/test_json.py
Labels: chore

#1794 Ensure redis_connect_func is set on uds connection
  redis/connection.py
Labels: bug

#1791 Single sourcing the package version
  redis/__init__.py
  setup.py
Labels: bug

#1790 Add CI action to install package from commit hash (#1781)
  .github/workflows/integration.yaml
Labels: chore

#1797 Socket not closing after server disconnect
  redis/connection.py
  tests/test_connection.py
Labels: bug

#1782 Support for password-encrypted SSL private keys
  .github/workflows/install_and_test.sh
  .github/workflows/integration.yaml
  .gitignore
  CONTRIBUTING.md
  dev_requirements.txt
  docker/base/Dockerfile
  docker/base/Dockerfile.cluster
  docker/base/Dockerfile.sentinel
  docker/base/Dockerfile.stunnel
  docker/stunnel/conf/redis.conf
  docker/stunnel/create_certs.sh
  redis/client.py
  redis/connection.py
  tasks.py
  tests/conftest.py
  tests/test_ssl.py
  tox.ini
Labels: feature

#1814 Allow ssl_ca_path with rediss:// urls
  redis/client.py
Labels: feature

#1818 JSON set_file and set_path support
  redis/commands/json/commands.py
  tests/test_json.py
Labels: feature, 4.1.0

#1822 Update redismodules.rst
  docs/redismodules.rst
Labels: chore

#1819 Fixed MovedError, and stopped iterating through startup nodes when slots are fully covered
  redis/cluster.py
Labels: bug, 4.1.0

#1549 Support WRITE in CLIENT PAUSE
  redis/commands/core.py
  tests/test_commands.py
  tests/test_json.py
Labels: feature, 4.1.0

#1823 Fixing exception in listen
  redis/client.py
Labels: bug

#1612 Support CLIENT TRACKING
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, 4.1.0

#1824 Support for RESET command since Redis 6.2.0
  redis/client.py
  redis/commands/core.py
  tests/test_commands.py
Labels: feature

#1827 Removing lots-of-pythons container
  CONTRIBUTING.md
  tox.ini
Labels: chore

#1737 Fixing read race condition during pubsub
  redis/client.py
  tests/test_pubsub.py
Labels: bug

#1821 Retry on error exception and timeout fixes
  redis/cluster.py
  tests/test_cluster.py
Labels: bug

#1825 Support for SELECT
  redis/commands/core.py
  tests/test_commands.py
Labels: feature

#1829 Marking STRALGO as prior to redis 7
  tests/test_commands.py
Labels: chore

#1831 SRTALGO - skip for redis versions greater than 7.0.0
  tests/test_commands.py
Labels: chore

#1820 OCSP stapling support
  redis/client.py
  redis/connection.py
  redis/exceptions.py
  redis/ocsp.py
  redis/utils.py
  setup.py
  tasks.py
  tests/conftest.py
  tests/test_ssl.py
  tox.ini
Labels: feature, 4.1.0

#1835 Connection examples
  docs/conf.py
  docs/examples.rst
  docs/examples/.ipynb_checkpoints/connection_example-checkpoint.ipynb
  docs/examples/README.md
  docs/examples/connection_example.ipynb
  docs/index.rst
  docs/requirements.txt
  tasks.py
  tox.ini
Labels: chore

#1841 Documentation cleanup
  docs/commands.rst
  docs/connections.rst
  docs/index.rst
  docs/redis_cluster_commands.rst
  docs/redis_commands.rst
  docs/redismodules.rst
  docs/sentinel_commands.rst
  redis/client.py
  redis/cluster.py
  redis/commands/graph/commands.py
  redis/commands/search/commands.py
  redis/connection.py
  redis/sentinel.py
Labels: bug

#1842 Support for unstable docker
  CONTRIBUTING.md
  docker/base/Dockerfile.unstable
  docker/unstable/redis.conf
  tox.ini
Labels: chore
