Repository redis/redis-py, pull requests merged in 2021-11, with the labels that each got.

#1665 Added boolean parsing to PEXPIRE and PEXPIREAT
  redis/client.py
  tests/test_commands.py
Labels: bug, breakingchange

#1666 Improvements to JSON coverage
  redis/commands/helpers.py
  redis/commands/json/__init__.py
  redis/commands/json/commands.py
  redis/commands/json/decoders.py
  redis/commands/json/path.py
  requirements.txt
  setup.py
  tests/test_json.py
  tox.ini
Labels: breakingchange

#1667 SMISMEMBER support
  redis/commands/core.py
  tests/test_commands.py
Labels: feature

#1578 Fix garbage collection deadlock
  dev_requirements.txt
  redis/connection.py
  tests/test_pubsub.py
Labels: help wanted, bug

#1672 Fix georadius tests
  tests/test_commands.py
Labels: chore

#1671 Export Sentinel, and SSL like other classes
  README.md
  redis/__init__.py
  redis/sentinel.py
Labels: bug

#1674 Re-enable pipeline support for JSON and TimeSeries
  redis/commands/helpers.py
  redis/commands/json/__init__.py
  redis/commands/json/commands.py
  redis/commands/timeseries/__init__.py
  tests/test_json.py
  tests/test_timeseries.py
  tox.ini
Labels: bug

#1676 Removing dependency on six
  redis/commands/search/_util.py
  redis/commands/search/aggregation.py
  redis/commands/search/commands.py
  redis/commands/search/document.py
  redis/commands/search/query.py
  redis/commands/search/querystring.py
  redis/commands/search/result.py
  redis/commands/search/suggestion.py
Labels: bug

#1677 4.0.0 rc2 versioning
  redis/__init__.py
Labels: chore

#1675 Docstring improvements for Redis class
  redis/client.py
Labels: chore

#1679 Test function renames, to match standards
  tests/test_timeseries.py
Labels: chore

#1680 Sleep for flaky search test
  tests/test_search.py
Labels: chore

#1678 Tests to validate built python packages
  .github/workflows/install_and_test.sh
  .github/workflows/integration.yaml
  dev_requirements.txt
  tasks.py
Labels: chore

#1681 Test to validate custom JSON decoders
  dev_requirements.txt
  tests/test_json.py
Labels: chore

#1689 Updating codecov rules
  codecov.yml
Labels: chore

#1691 Adding RediSearch/RedisJSON tests
  tests/test_search.py
Labels: chore

#1692 Response parsing occasionally fails to parse floats
  redis/commands/helpers.py
  tests/test_helpers.py
Labels: bug, breakingchange

#1696 ck testfixes
  tests/conftest.py
  tests/test_connection.py
  tests/test_connection_pool.py
  tests/test_monitor.py
  tests/test_multiprocessing.py
  tests/test_pubsub.py
  tests/test_sentinel.py
Labels: chore

#1697 Restoring ZRANGE desc for Redis < 6.2.0
  redis/commands/core.py
  tests/test_commands.py
Labels: bug

#1700 Fixes to allow --redis-url to pass through all tests
  tests/conftest.py
  tests/test_commands.py
  tests/test_connection_pool.py
  tests/test_monitor.py
  tests/test_pubsub.py
  tests/test_scripting.py
Labels: chore

#1701 Improve documentation about Lock
  redis/lock.py
Labels: chore

#1703 Unit tests fixes for compatibility
  redis/client.py
  redis/commands/core.py
  redis/commands/redismodules.py
  redis/commands/search/__init__.py
  redis/commands/timeseries/__init__.py
  tests/conftest.py
  tests/test_commands.py
  tests/test_connection.py
Labels: chore

#1706 Call HSET after FT.CREATE to avoid keyspace scan
  tests/test_search.py
Labels: chore

#1705 FT.EXPLAINCLI intentionally raising NotImplementedError
  redis/commands/search/commands.py
  tests/test_search.py
Labels: feature

#1707 Re-enabling read-the-docs
  .readthedocs.yml
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  tox.ini
Labels: chore

#1726 Better removal of hiredis warning
  redis/__init__.py
  redis/connection.py
Labels: bug, 4.0.next

#1723 fix: adding sentinelcommands to redis client
  redis/client.py
Labels: bug, 4.0.next

#1719 Adding links to redis documents in function calls
  redis/commands/core.py
Labels: chore

#1742 4.1.0rc1
  redis/__init__.py
Labels: chore, 4.1.0

#1660 Adding RedisCluster client to support Redis Cluster Mode
  .github/workflows/install_and_test.sh
  CONTRIBUTING.md
  README.md
  docker/base/Dockerfile.cluster
  docker/base/create_cluster.sh
  docker/cluster/redis.conf
  redis/__init__.py
  redis/client.py
  redis/cluster.py
  redis/commands/__init__.py
  redis/commands/cluster.py
  redis/commands/core.py
  redis/commands/parser.py
  redis/connection.py
  redis/crc.py
  redis/exceptions.py
  redis/utils.py
  tasks.py
  tests/conftest.py
  tests/test_cluster.py
  tests/test_command_parser.py
  tests/test_commands.py
  tests/test_connection.py
  tests/test_connection_pool.py
  tests/test_json.py
  tests/test_lock.py
  tests/test_monitor.py
  tests/test_pipeline.py
  tests/test_pubsub.py
  tests/test_scripting.py
  tests/test_sentinel.py
  tox.ini
Labels: 4.1.0

#1684 GitHub release improvements
  .github/workflows/pypi-publish.yaml
Labels: chore, 4.1.0

#1747 RedisJSON 2.0.4 behaviour support
  tests/conftest.py
  tests/test_json.py
  tests/test_timeseries.py
Labels: feature, 4.1.0

#1738 COMMAND GETKEYS support
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, 4.1.0

#1731 Adding support for non-decodable commands
  redis/client.py
  redis/commands/core.py
  redis/connection.py
  redis/sentinel.py
Labels: feature, 4.1.0

#1750 Fixing COMMAND GETKEYS tests
  .gitignore
  tasks.py
  tests/test_commands.py
  tox.ini
Labels: chore, 4.1.0

#1713 Improve code coverage for aggregation tests
  redis/commands/search/aggregation.py
  tests/test_search.py
Labels: chore, 4.1.0

#1727 Support RediSearch FT.PROFILE command
  redis/commands/helpers.py
  redis/commands/search/commands.py
  tests/test_helpers.py
  tests/test_search.py
Labels: feature, 4.1.0

#1743 Splitting documentation for read the docs
  README.md
  docs/backoff.rst
  docs/conf.py
  docs/connections.rst
  docs/exceptions.rst
  docs/genindex.rst
  docs/index.rst
  docs/lock.rst
  docs/redis_core_commands.rst
  docs/redismodules.rst
  docs/requirements.txt
  docs/retry.rst
  docs/sentinel_commands.rst
  redis/commands/timeseries/commands.py
  tasks.py
  tox.ini
Labels: chore, 4.1.0

#1730 Fixing deprecating distutils (PEP 632)
  redis/connection.py
  requirements.txt
  setup.py
  tox.ini
Labels: bug, 4.1.0

#1751 Removing duplication of Script class
  redis/client.py
Labels: chore, 4.1.0

#1745 Updating PR template
  .github/PULL_REQUEST_TEMPLATE.md
  examples/README.md
Labels: chore

#1759 Pyupgrade + flynt + f-strings
  benchmarks/base.py
  benchmarks/basic_operations.py
  benchmarks/command_packer_benchmark.py
  dev_requirements.txt
  redis/client.py
  redis/cluster.py
  redis/commands/cluster.py
  redis/commands/core.py
  redis/commands/helpers.py
  redis/commands/json/path.py
  redis/commands/parser.py
  redis/commands/search/__init__.py
  redis/commands/search/aggregation.py
  redis/commands/search/commands.py
  redis/commands/search/document.py
  redis/commands/search/field.py
  redis/commands/search/indexDefinition.py
  redis/commands/search/query.py
  redis/commands/search/querystring.py
  redis/commands/search/reducers.py
  redis/commands/search/result.py
  redis/commands/search/suggestion.py
  redis/commands/timeseries/info.py
  redis/connection.py
  redis/sentinel.py
  tasks.py
  tests/conftest.py
  tests/test_cluster.py
  tests/test_commands.py
  tests/test_connection.py
  tests/test_multiprocessing.py
  tests/test_pipeline.py
  tests/test_pubsub.py
  tests/test_search.py
  tests/test_timeseries.py
  tox.ini
Labels: chore, 4.1.0

#1760 Updating cluster docker location
  tox.ini
Labels: chore, 4.1.0

#1711 Link Documents for all module commands
  docs/index.rst
  redis/commands/json/commands.py
  redis/commands/search/commands.py
  redis/commands/timeseries/commands.py
Labels: chore, 4.1.0

#1761 Pre-4.1.0rc2 version bump
  redis/__init__.py
Labels: chore

#1673 Adding RedisGraph support
  redis/commands/graph/__init__.py
  redis/commands/graph/commands.py
  redis/commands/graph/edge.py
  redis/commands/graph/exceptions.py
  redis/commands/graph/node.py
  redis/commands/graph/path.py
  redis/commands/graph/query_result.py
  redis/commands/helpers.py
  redis/commands/redismodules.py
  setup.py
  tests/test_graph.py
  tests/test_graph_utils/__init__.py
  tests/test_graph_utils/test_edge.py
  tests/test_graph_utils/test_node.py
  tests/test_graph_utils/test_path.py
  tox.ini
Labels: feature, 4.1.0
