Repository redis/redis-py, pull requests merged in 2022-12, with the labels that each got.

#2464 Wrong number of arguments for `geosearch` command
  redis/commands/core.py
Labels: bug

#2463 Added a replacement for the default cluster node in the event of failure.
  CHANGES
  redis/asyncio/cluster.py
  redis/cluster.py
  tests/test_asyncio/test_cluster.py
  tests/test_cluster.py
Labels: bug

#2454 Async: added 'blocking' argument to call lock method
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  tests/test_asyncio/test_lock.py
Labels: bug

#2471 Async clusters: Support creating locks inside async functions
  redis/asyncio/cluster.py
Labels: feature

#2466 Use explicit index name in RediSearch example
  docs/redismodules.rst
Labels: maintenance

#2473 Removing Deprecated LGTM
  README.md
Labels: maintenance

#2475 Updating dev dependencies
  dev_requirements.txt
  redis/ocsp.py
  tests/test_asyncio/test_graph.py
  tests/test_graph.py
Labels: maintenance

#2485 Version 4.4.0
  setup.py
  tox.ini
Labels: maintenance

#2486 Updating graph tests to support new execution plan
  tests/test_asyncio/test_graph.py
  tests/test_graph.py
  tox.ini
Labels: maintenance

#2501 Raising NotImplementedError for certain LATENC commands
  redis/commands/core.py
  tests/test_commands.py
Labels: feature

#2503 Add support for certain LATENCY commands
  redis/cluster.py
  redis/commands/core.py
  tests/test_commands.py
Labels: feature

#2482 Combine auto-concatenated strings
  benchmarks/basic_operations.py
  redis/asyncio/client.py
  redis/asyncio/lock.py
  redis/client.py
  redis/cluster.py
  redis/commands/core.py
  redis/commands/graph/node.py
  redis/commands/search/commands.py
  redis/connection.py
  redis/lock.py
  tests/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_pipeline.py
  tests/test_asyncio/test_pubsub.py
  tests/test_cluster.py
  tests/test_commands.py
  tests/test_connection_pool.py
  tests/test_pipeline.py
Labels: maintenance

#2492 Switch docs to furo theme
  docs/_static/redis-cube-red-white-rgb.svg
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
Labels: maintenance

#2452 Add OpenTelemetry example with Uptrace backend
  docs/conf.py
  docs/examples.rst
  docs/examples/opentelemetry/README.md
  docs/examples/opentelemetry/config/alertmanager.yml
  docs/examples/opentelemetry/config/otel-collector.yaml
  docs/examples/opentelemetry/config/vector.toml
  docs/examples/opentelemetry/docker-compose.yml
  docs/examples/opentelemetry/image/redis-py-trace.png
  docs/examples/opentelemetry/main.py
  docs/examples/opentelemetry/requirements.txt
  docs/examples/opentelemetry/uptrace.yml
  docs/examples/opentelemetry_api_examples.ipynb
  docs/images/opentelemetry/distributed-tracing.png
  docs/images/opentelemetry/redis-metrics.png
  docs/images/opentelemetry/redis-py-trace.png
  docs/images/opentelemetry/tree-of-spans.png
  docs/index.rst
  docs/opentelemetry.rst
Labels: maintenance

#2527 Fix `JSON.ARRINDEX` test
  tests/test_json.py
Labels: maintenance

#2519 Add TIMEOUT to query class
  redis/commands/search/query.py
  tests/test_asyncio/test_search.py
  tests/test_search.py
Labels: feature

#2495 add timeout parameter for SentinelManagedConnection
  CHANGES
  redis/asyncio/sentinel.py
Labels: feature

#2520 Fix for Unhandled exception related to self.host with unix socket
  CHANGES
  redis/connection.py
Labels: bug

#2494 Allow EVAL_RO and EVALSHA_RO to be routed to read replica
  redis/commands/cluster.py
  redis/commands/core.py
  tests/test_cluster.py
  tests/test_scripting.py
Labels: feature

#2514 Support for resetchannels since Redis 6.2.0
  redis/commands/core.py
Labels: feature
