Repository redis/redis-py, pull requests merged in 2022-01, with the labels that each got.

#1850 Support test with redis unstable docker
  tests/conftest.py
Labels: chore

#1867 `setup.py`: Add project_urls for PyPI
  setup.py
Labels: chore

#1847 FT.CREATE - support MAXTEXTFIELDS, TEMPORARY, NOHL, NOFREQS, SKIPINITIALSCAN
  redis/commands/search/commands.py
  tests/test_search.py
Labels: feature

#1854 Allowing poetry and redis-py to install together
  setup.py
Labels: chore

#1855 Typo and typing in GraphCommands documentation
  redis/commands/graph/commands.py
Labels: chore

#1845 Clusters should optionally require full slot coverage
  redis/cluster.py
  tests/test_cluster.py
Labels: bug

#1853 Set keys var otherwise variable not created
  redis/commands/parser.py
Labels: bug

#1870 syncing requirements
  requirements.txt
Labels: chore

#1832 get_connection: catch OSError too
  redis/connection.py
Labels: bug

#1876 Triple quote docstrings in client.py PEP 257
  redis/client.py
Labels: chore

#1877 Timeseries docs fix
  docs/redismodules.rst
Labels: bug

#1874 Define incr/decr as aliases of incrby/decrby
  redis/commands/core.py
Labels: feature

#1881 More parallel CI workflows
  .github/workflows/integration.yaml
Labels: chore

#1873 OCSP Stapling Support
  .github/workflows/integration.yaml
  docs/examples.rst
  docs/examples/connection_examples.ipynb
  docs/examples/ssl_connecton_examples.ipynb
  redis/client.py
  redis/connection.py
  redis/ocsp.py
  setup.py
  tasks.py
  tests/test_ssl.py
  tox.ini
Labels: feature

#1879 Add retries to connections in Sentinel Pools
  redis/sentinel.py
Labels: feature

#1885 direct link to readthedocs
  README.md
Labels: chore

#1897 Fix link in the main page
  docs/index.rst
Labels: chore

#1888 README code snippets formatted to highlight properly
  README.md
Labels: chore

#1895 Added retry mechanism on socket timeouts when connecting to the server
  redis/connection.py
  redis/retry.py
  tests/test_connection.py
Labels: feature

#1901 Fixing TypeError in GraphCommands.explain
  redis/commands/graph/commands.py
Labels: bug

#1903 Fixing AttributeError in UnixDomainSocketConnection
  redis/connection.py
Labels: bug

#1905 Fixing AttributeError on some connection errors
  redis/connection.py
Labels: bug

#1900 cluster script fixes to support future cluster versions and redis unstable
  docker/base/Dockerfile.cluster
  docker/base/Dockerfile.unstable_cluster
  docker/base/Dockerfile.unstable_sentinel
  docker/base/create_cluster.sh
Labels: chore

#1906 Fixing LMOVE, BLMOVE returning an incorrect response
  redis/client.py
Labels: bug

#1907 Invalid OCSP certificates should raise ConnectionError on failed validation
  redis/ocsp.py
  tests/test_ssl.py
Labels: feature

#1904 4.1.2
  setup.py
Labels: chore

#1908 For tests, increasing wait time for the cluster
  tests/conftest.py
Labels: chore

#1915 Update changes file with changes since 4.0.0-beta2
  CHANGES
Labels: chore

#1914 Fixing volume for unstable_cluster docker
  tox.ini
Labels: chore
