Repository redis/redis-py, pull requests merged in 2022-03, with the labels that each got.

#2029 Fixing TimesSeries tests
  tests/test_timeseries.py
Labels: maintenance

#2013 Implement locks for RedisCluster
  CHANGES
  redis/asyncio/client.py
  redis/client.py
  redis/cluster.py
  redis/lock.py
  tests/test_lock.py
Labels: feature

#2025 Fix typo in comment
  redis/typing.py
Labels: maintenance

#2011 Fix asyncio retry.py typing
  redis/asyncio/retry.py
Labels: maintenance

#2010 Add async typing support to commands' returns
  redis/commands/core.py
Labels: maintenance

#2032 Add support for JSON, TIMESERIES, BLOOM & GRAPH commands in cluster
  redis/cluster.py
  redis/commands/cluster.py
  redis/commands/json/__init__.py
  redis/commands/parser.py
  redis/commands/timeseries/__init__.py
  tests/test_bloom.py
  tests/test_graph.py
  tests/test_search.py
  tests/test_timeseries.py
  tox.ini
Labels: feature

#2006 Add support for HSET items
  CHANGES
  redis/commands/core.py
  tests/test_commands.py
  tests/test_search.py
Labels: feature

#2016 Add cluster support for functions
  redis/cluster.py
  redis/commands/cluster.py
  tests/test_function.py
  tox.ini
Labels: feature, redis-7

#1860 Add support for EXPIRETIME
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#1861 Add support for PEXPIRETIME
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2038 Add pipeline support for Search
  redis/commands/search/__init__.py
  redis/commands/search/commands.py
  tests/test_search.py
Labels: feature

#2043 Fix typo
  redis/commands/search/commands.py
Labels: maintenance

#2017 Add support for CLUSTER ADDSLOTSRANGE
  redis/client.py
  redis/cluster.py
  redis/commands/cluster.py
  tests/test_cluster.py
Labels: feature, redis-7

#2018 Add support for CLUSTER DELSLOTSRANGE
  redis/client.py
  redis/cluster.py
  redis/commands/cluster.py
  tests/test_cluster.py
Labels: feature, redis-7

#2019 Add support for CLUSTER LINKS
  redis/commands/cluster.py
  tests/test_cluster.py
Labels: feature, redis-7

#2045 Fixed typo in word 'sentinel'
  redis/commands/sentinel.py
Labels: maintenance

#2046 redis_connect_func
  redis/asyncio/connection.py
Labels: maintenance

#1458 Fix: avoiding issue with PytestUnraisableExceptionWarning
  redis/client.py
Labels: Stale, maintenance

#2048 Add support to use certificates from string in ssl connection
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
  tests/test_ssl.py
Labels: feature

#2002 Add support for EXPIRE command's options
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2024 Add support for EXPIREAT command's options
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2026 Add support for PEXPIRE command's option
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2027 Add support for PEXPIREAT's options
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2042 Add support for SEARCH commands in cluster
  redis/cluster.py
  tests/conftest.py
  tests/test_search.py
Labels: feature

#1858 Add support for SORT_RO
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2054 [CLUSTER] Fix scan command cursors & Fix scan_iter
  CHANGES
  redis/cluster.py
  redis/commands/cluster.py
  tests/test_cluster.py
Labels: bug

#2041 Support for Vector Fields for Vector Similarity Search
  redis/commands/search/field.py
  tests/test_search.py
Labels: feature

#2062 Make typing_extensions conditional to Python < 3.8
  requirements.txt
  setup.py
Labels: maintenance

#2071 Add dialect support for RediSearch queries
  redis/commands/search/query.py
  tests/test_search.py
Labels: feature
