Repository redis/redis-py, pull requests merged in 2022-09, with the labels that each got.

#2364 Change return type of parse_boolean from int to bool
  redis/commands/graph/query_result.py
Labels: bug

#2363 Mark `TOPK.COUNT` as deprecated
  redis/commands/bf/commands.py
  tests/test_asyncio/test_bloom.py
  tests/test_bloom.py
Labels: maintenance

#2367 Fixing async test for module list
  tests/test_asyncio/test_commands.py
Labels: maintenance

#2368 Fix/readme links
  CHANGES
  README.md
Labels: maintenance

#2381 Adding support for readable test results
  .github/workflows/integration.yaml
  tox.ini
Labels: maintenance

#2392 Add support for new TDIGEST features and changes
  .github/workflows/integration.yaml
  redis/commands/bf/__init__.py
  redis/commands/bf/commands.py
  redis/commands/bf/info.py
  redis/commands/bf/utils.py
  tests/test_asyncio/test_bloom.py
  tests/test_bloom.py
Labels: experimental

#2385 Support Hiredis >= 1.x only (remove `packaging` dependency)
  CHANGES
  README.md
  dev_requirements.txt
  redis/connection.py
  redis/utils.py
  requirements.txt
  setup.py
Labels: maintenance

#2389 Update GitHub Actions versions
  .github/workflows/codeql-analysis.yml
  .github/workflows/integration.yaml
  .github/workflows/pypi-publish.yaml
Labels: maintenance

#2308 Dev/no lock
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connection.py
Labels: feature

#2402 Updating VecSim search example to highlight dialect
  docs/examples/search_vector_similarity_examples.ipynb
Labels: maintenance

#2393 FT.SEARCH: Fixing aggregation request argument for LIMIT
  redis/commands/search/aggregation.py
Labels: bug

#2104 Catch `Exception` and not `BaseException` in the `Connection`
  redis/asyncio/connection.py
  redis/connection.py
  tests/test_asyncio/test_pubsub.py
  tests/test_pubsub.py
Labels: bug, breakingchange

#2356 Add `nowait` flag to `asyncio.Connection.disconnect()`
  CHANGES
  redis/asyncio/connection.py
  tests/test_asyncio/test_pubsub.py
Labels: feature

#2360 Dev/no can read
  redis/asyncio/client.py
  redis/asyncio/connection.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_pubsub.py
Labels: maintenance

#2403 4.4.0rc2
  setup.py
Labels: maintenance

#2295 Simplify async timeouts and allowing `timeout=None` in `PubSub.get_message()` to wait forever
  CHANGES
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/client.py
  tests/test_asyncio/test_pubsub.py
Labels: feature, maintenance
