Repository redis/redis-py, pull requests merged in 2022-05, with the labels that each got.

#2144 Rename 'update_supported_erros' to 'update_supported_errors' in Retry module
  redis/connection.py
  redis/retry.py
Labels: bug

#2147 Implemented LATENCY HISTOGRAM by always throwing NotImplementedError
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2155 Fix incorrect return annotation in asyncio.lock
  redis/asyncio/lock.py
Labels: maintenance

#2158 Enable DEBUG and MODULE commands in redis 7 docker images
  docker/redis7/master/redis.conf
Labels: maintenance, redis-7

#2148 Async Connection: Allow `PubSub.run()` without previous `subscribe()`
  redis/asyncio/client.py
  tests/test_asyncio/test_pubsub.py
Labels: feature

#2157 Add support for redis 7 streams features
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2163 Skip GRAPH.CONFIG test in redis enterprise
  tests/test_graph.py
Labels: maintenance

#2161 ACL SETUSER - add selectors and key based permissions
  redis/client.py
  redis/commands/core.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: feature, redis-7

#2167 Add unittest for PubSub.connect()
  tests/test_asyncio/test_pubsub.py
Labels: maintenance

#2140 Replace OSError exceptions from `can_read` with `redis.ConnectionError`
  redis/asyncio/connection.py
  redis/connection.py
Labels: breakingchange

#2099 Add Async RedisCluster
  benchmarks/cluster_async.py
  docs/conf.py
  docs/connections.rst
  docs/requirements.txt
  redis/asyncio/__init__.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/asyncio/parser.py
  redis/client.py
  redis/cluster.py
  redis/commands/__init__.py
  redis/commands/cluster.py
  redis/commands/parser.py
  redis/crc.py
  redis/typing.py
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_lock.py
  tests/test_asyncio/test_retry.py
  tests/test_cluster.py
  tox.ini
  whitelist.py
Labels: feature

#2149 Add support for COMMAND LIST
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2151 Add support for CLUSTER SHARDS
  redis/cluster.py
  redis/commands/cluster.py
  tests/test_cluster.py
Labels: feature, redis-7

#2170 Get command keys for subcommands
  redis/client.py
  redis/cluster.py
  redis/commands/parser.py
  tests/test_cluster.py
  tests/test_commands.py
Labels: feature, redis-7

#2175 Fix asyncio Search crash, and versioning 4.3.1
  redis/commands/search/__init__.py
  setup.py
Labels: bug

#2191 Fix Linting and Test Failures
  redis/commands/search/commands.py
  tests/test_asyncio/test_json.py
  tests/test_json.py
Labels: maintenance

#2203 fix: changed list type to single element type
  redis/commands/core.py
Labels: maintenance

#2199 async_cluster: add pipeline support
  docs/connections.rst
  redis/asyncio/cluster.py
  redis/cluster.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_pipeline.py
Labels: feature

#2182 Fix tests for Redis 7
  redis/cluster.py
  redis/commands/parser.py
  tests/test_asyncio/test_commands.py
  tests/test_cluster.py
  tests/test_command_parser.py
  tests/test_commands.py
  tests/test_encoding.py
  tests/test_function.py
  tests/test_scripting.py
Labels: maintenance
