Repository redis/redis-py, pull requests merged in 2022-08, with the labels that each got.

#2317 Add support for `TDIGEST.QUANTILE` extensions
  redis/commands/bf/__init__.py
  redis/commands/bf/commands.py
  redis/commands/bf/utils.py
  tests/test_asyncio/test_bloom.py
  tests/test_bloom.py
Labels: feature, breakingchange

#2311 Replace `ensure_future` with `create_task`
  redis/asyncio/cluster.py
  redis/commands/cluster.py
  tests/test_asyncio/compat.py
Labels: maintenance

#2315 Change `dropindex()` to use `FT.DROPINDEX` (instead `FT.DROP`)
  redis/commands/search/commands.py
Labels: bug, breakingchange

#2316 Fix async SEARCH pipeline
  redis/commands/search/__init__.py
  tests/test_asyncio/test_search.py
Labels: bug, async

#2319 Support TDIGEST.MERGESTORE and make compression optional on TDIGEST.CREATE
  redis/commands/bf/commands.py
  tests/test_asyncio/test_bloom.py
  tests/test_bloom.py
Labels: feature

#2322 Search test - Ignore order of the items in the response
  tests/test_asyncio/test_search.py
  tests/test_search.py
Labels: maintenance

#2321 4.4.0rc1
  setup.py
Labels: maintenance

#2300 Add TDIGEST.TRIMMED_MEAN
  redis/commands/bf/__init__.py
  redis/commands/bf/commands.py
  tests/test_bloom.py
Labels: feature

#2324 Add support for WITHSUFFIXTRIE to FT.CREATE
  redis/commands/search/field.py
  tests/test_asyncio/test_search.py
  tests/test_search.py
Labels: experimental

#2335 Fix GRAPH.LIST & TDIGEST.QUANTILE tests
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_graph.py
  tests/test_bloom.py
  tests/test_graph.py
Labels: maintenance

#2332 Adding dependency vulnerability scanning to the CI process
  .github/workflows/integration.yaml
Labels: maintenance

#2348 Fix tdigest.create
  redis/commands/bf/commands.py
Labels: experimental

#2340 Add BITFIELD_RO
  redis/commands/core.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: feature

#2341 Fix typo work -> word
  README.md
Labels: maintenance

#2343 Be more strict about url scheme parsing
  redis/connection.py
  tests/test_connection_pool.py
Labels: maintenance

#2358 Fix TimeSeries range aggregation (twa) tests
  tests/test_asyncio/test_timeseries.py
  tests/test_timeseries.py
Labels: maintenance

#2362 Update LICENSE
  LICENSE
Labels: maintenance

#2361 Fix type hint annotations of expire time
  redis/typing.py
Labels: maintenance

#2331 Adding reserve as an alias for create, so that we have BF.RESERVE and CF.RESERVE accuratenly supported
  redis/commands/bf/commands.py
  tests/test_bloom.py
Labels: feature

#2327 Document Redis(single_connection_client)
  redis/client.py
Labels: maintenance
