Repository redis/redis-py, pull requests merged in 2022-10, with the labels that each got.

#2408 Remove `weight` parameter from `TDIGEST.ADD` and fix tests
  redis/commands/bf/commands.py
  redis/commands/bf/info.py
  tests/test_asyncio/test_bloom.py
  tests/test_bloom.py
Labels: experimental

#2409 Updating docker system to allow for M1 development
  tox.ini
Labels: maintenance

#2424 Fixing invalid vulnerability report
  .github/workflows/integration.yaml
Labels: maintenance

#2421 Fix `TIMESERIES` (round floats) and `JSON` tests
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_timeseries.py
  tests/test_json.py
  tests/test_search.py
  tests/test_timeseries.py
Labels: maintenance

#2422 Release drafter formatting improvement: titles
  .github/release-drafter-config.yml
Labels: maintenance

#2426 Updating the docker image for the module cluster
  tox.ini
Labels: maintenance

#2430 Fixing RedisBloom tests for TDIGEST.RANK results
  tests/test_asyncio/test_bloom.py
  tests/test_bloom.py
Labels: maintenance

#2411 Test `test_get_moveable_keys` was broken
  tests/test_command_parser.py
Labels: maintenance

#2412 fix: catch OSError on asyncio
  redis/asyncio/connection.py
Labels: bug

#2431 Tidy up asyncio examples.
  docs/examples/asyncio_examples.ipynb
Labels: maintenance, hacktoberfest-accepted

#2435 Add missing dots to README.md
  README.md
Labels: maintenance

#2428 Python 3.11 in CI
  .github/workflows/integration.yaml
Labels: maintenance

#2439 Fix KeyError in async cluster - initialize before execute multi key commands
  redis/commands/cluster.py
  tests/test_asyncio/test_cluster.py
Labels: bug, async, cluster

#2438 Remove default None value from LMPOP direction argument
  redis/commands/core.py
Labels: bug

#2440 Linking to the latest pre-release
  README.md
Labels: maintenance

#2386 Supply chain risk reduction: remove dependency on library named `deprecated`
  CHANGES
  redis/commands/bf/commands.py
  redis/commands/json/commands.py
  redis/commands/search/commands.py
  redis/utils.py
  requirements.txt
  setup.py
Labels: maintenance
