Repository redis/redis-py, pull requests merged in 2022-04, with the labels that each got.

#2083 Vector similarity search example
  docs/examples.rst
  docs/examples/search_vector_similarity_examples.ipynb
Labels: maintenance

#2082 Clean up test supoort enterprise environments
  tests/conftest.py
  tests/test_cluster.py
  tests/test_command_parser.py
  tests/test_commands.py
  tests/test_lock.py
  tests/test_scripting.py
  tests/test_search.py
  tox.ini
Labels: maintenance

#2078 Clarify bit type in setbit/getbit documentation
  redis/commands/core.py
Labels: maintenance

#2069 Cluster commands linkdocs
  redis/commands/cluster.py
  redis/commands/core.py
Labels: maintenance

#2070 Fix disable decode for dump command on asyncio
  redis/asyncio/client.py
Labels: bug

#2077 always clear reference to closed reader/writer
  CHANGES
  redis/asyncio/connection.py
Labels: bug

#2079 fix asynic/client.py's import
  redis/asyncio/client.py
Labels: bug

#2080 Extended "CLUSTER NODES" parser to support special slot entries
  redis/client.py
  tests/test_cluster.py
Labels: feature, breakingchange

#2087 Async tests for redis commands, json, bloom, timeseries
  redis/asyncio/client.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_timeseries.py
  tox.ini
Labels: maintenance

#2141 Add support for COMMAND GETKEYSANDFLAGS
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2142 CONFIG GET - add the ability to pass multiple pattern parameters in one call
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2143 CONFIG SET - add the ability to set multiple parameters in one call
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2145 INFO - add support for taking multiple section arguments
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2146 Add support for MODULE LOADEX
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#2092 Fix incorrect return statement in auth (#2086)
  CHANGES
  redis/commands/core.py
  tests/test_commands.py
Labels: bug

#2093 Update xtrim type annotation
  redis/commands/core.py
Labels: maintenance

#2097 fix execute_command() determine nodes error when no key command
  redis/cluster.py
Labels: bug

#2110 `Retry()`: Support negative `retries` value
  CHANGES
  redis/asyncio/retry.py
  redis/retry.py
  tests/test_asyncio/test_retry.py
  tests/test_retry.py
Labels: feature

#2096 Add async supoort for SEARCH commands
  redis/asyncio/client.py
  redis/commands/__init__.py
  redis/commands/redismodules.py
  redis/commands/search/__init__.py
  redis/commands/search/commands.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_search.py
  tests/test_asyncio/testdata/jsontestdata.py
  tests/test_asyncio/testdata/titles.csv
  tests/test_asyncio/testdata/will_play_text.csv.bz2
Labels: feature

#2094 Minor cleanups in commands/cluster.py
  redis/commands/cluster.py
Labels: maintenance
