Repository redis/redis-py, pull requests merged in 2022-11, with the labels that each got.

#2378 fix docs for password protected socket access
  CHANGES
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
Labels: maintenance

#2446 Enable AsyncIO cluster mode lock
  CHANGES
  redis/asyncio/cluster.py
  redis/asyncio/lock.py
  redis/commands/core.py
  tests/test_asyncio/test_lock.py
Labels: feature

#2302 Fix special response parsing options handling
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/client.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: bug

#2261 CredentialsProvider class added to support password rotation
  CHANGES
  docs/examples/asyncio_examples.ipynb
  docs/examples/connection_examples.ipynb
  redis/__init__.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
  redis/credentials.py
  tests/test_asyncio/test_credentials.py
  tests/test_credentials.py
Labels: feature

#2377 Failover handling improvements for RedisCluster and Async RedisCluster
  CHANGES
  redis/__init__.py
  redis/asyncio/__init__.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/backoff.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_retry.py
  tests/test_cluster.py
  tests/test_retry.py
Labels: bug

#2456 Retry documentation. (#2166)
  docs/backoff.rst
  docs/exceptions.rst
  docs/retry.rst
Labels: maintenance

#2455 Removed bad tokens from connection_examples.ipynb
  docs/examples/connection_examples.ipynb
Labels: maintenance

#2459 Fix Sentinel.execute_command to execute across the entire sentinel cluster
  CHANGES
  redis/sentinel.py
Labels: bug, breakingchange

#2444 GitHub Workflows security hardening
  .github/workflows/integration.yaml
  .github/workflows/pypi-publish.yaml
  .github/workflows/release-drafter.yml
  .github/workflows/stale-issues.yml
Labels: maintenance

#2478 Adding connection step to bloom filter examples
  docs/redismodules.rst
Labels: maintenance
