Repository redis/redis-py, pull requests merged in 2022-07, with the labels that each got.

#2263 Nightly run of integration tests
  .github/workflows/integration.yaml
Labels: maintenance

#2271 Use retry mechanism in async version of Connection objects
  CHANGES
  redis/asyncio/connection.py
  redis/asyncio/sentinel.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_sentinel_managed_connection.py
Labels: feature

#2278 Fix async connection.is_connected to return a boolean value
  redis/asyncio/connection.py
Labels: bug

#2259 fix: workaround asyncio bug on connection reset by peer
  redis/asyncio/connection.py
Labels: bug, async

#2270 Fix crash: key expire while search
  redis/commands/search/result.py
  tests/test_search.py
Labels: bug

#2274 docs: Fix a few typos
  redis/cluster.py
  redis/commands/core.py
  redis/ocsp.py
  tests/test_cluster.py
Labels: maintenance

#2280 async_cluster: fix concurrent pipeline
  redis/asyncio/cluster.py
  tests/test_asyncio/test_cluster.py
Labels: bug, async

#2296 Add support for TIMESERIES 1.8
  redis/commands/timeseries/commands.py
  redis/commands/timeseries/info.py
  tests/test_timeseries.py
Labels: feature, breakingchange

#2238 Remove verbose logging from `redis-py/redis/cluster.py`
  CHANGES
  redis/cluster.py
Labels: maintenance, breakingchange

#2269 redis stream example
  docs/examples.rst
  docs/examples/redis-stream-example.ipynb
Labels: maintenance

#2257 Fix: `start_id` type for `XAUTOCLAIM`
  CHANGES
  redis/commands/core.py
Labels: maintenance

#2267 Doc add timeseries example
  docs/examples.rst
  docs/examples/timeseries_examples.ipynb
Labels: maintenance

#2258 Fix warnings and resource usage problems in asyncio unittests
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_encoding.py
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_lock.py
  tests/test_asyncio/test_monitor.py
  tests/test_asyncio/test_pipeline.py
  tests/test_asyncio/test_pubsub.py
  tests/test_asyncio/test_scripting.py
  tests/test_asyncio/test_search.py
  tests/test_asyncio/test_sentinel.py
  tests/test_asyncio/test_timeseries.py
  tests/test_json.py
  tests/test_ssl.py
  tox.ini
Labels: maintenance

#2291 cleaning up the readme and moving docs into readthedocs
  README.md
  docs/advanced_features.rst
  docs/clustering.rst
  docs/index.rst
  docs/lua_scripting.rst
  redis/client.py
Labels: maintenance

#2217 async_cluster: fix max_connections/ssl & improve args
  redis/asyncio/cluster.py
  redis/cluster.py
  redis/exceptions.py
  tests/test_asyncio/test_cluster.py
Labels: bug, breakingchange, async

#2306 Drop python 3.6 support
  .github/workflows/integration.yaml
  CONTRIBUTING.md
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/asyncio/lock.py
  setup.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_encoding.py
  tests/test_asyncio/test_lock.py
  tests/test_asyncio/test_monitor.py
  tests/test_asyncio/test_pipeline.py
  tests/test_asyncio/test_pubsub.py
  tests/test_asyncio/test_scripting.py
  tests/test_asyncio/test_search.py
  tests/test_asyncio/test_sentinel.py
  tests/test_asyncio/test_timeseries.py
  tox.ini
Labels: maintenance, breakingchange

#2307 drop invocation of redismod_cluster docker
  tox.ini
Labels: maintenance

#2281 automatically reconnect pubsub when reading messages in blocking mode
  redis/asyncio/client.py
  redis/client.py
  tests/conftest.py
  tests/test_asyncio/compat.py
  tests/test_asyncio/test_pubsub.py
  tests/test_pubsub.py
Labels: bug

#2273 Add support for async GRAPH module
  redis/commands/graph/__init__.py
  redis/commands/graph/commands.py
  redis/commands/graph/query_result.py
  redis/commands/redismodules.py
  tests/test_asyncio/test_graph.py
Labels: feature, async

#2312 Fix typing on smembers command
  redis/commands/core.py
Labels: maintenance

#2313 Remove python2-only `__nonzero__` method from `cluster.py`
  redis/cluster.py
Labels: maintenance

#2314 Fix typo in README.md
  README.md
Labels: maintenance
