Repository redis/redis-py, pull requests merged in 2022-02, with the labels that each got.

#1922 Change json.clear test multi to be up to date with redisjson
  tests/test_json.py
Labels: chore

#1851 Add support for BZMPOP
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#1857 Add support for ZINTERCARD
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#1862 Add support for EVAL_RO
  redis/commands/core.py
  tests/test_scripting.py
Labels: feature, redis-7

#1863 Add support for EVALSHA_RO
  redis/commands/core.py
  tests/test_scripting.py
Labels: feature, redis-7

#1872 Fix naming conventions
  redis/commands/bf/__init__.py
  redis/commands/bf/commands.py
  redis/commands/graph/__init__.py
  redis/commands/graph/edge.py
  redis/commands/graph/node.py
  redis/commands/graph/query_result.py
  redis/commands/helpers.py
  redis/commands/json/commands.py
  redis/commands/json/path.py
  redis/commands/search/commands.py
  redis/commands/search/indexDefinition.py
  redis/commands/timeseries/commands.py
  tests/test_graph.py
  tests/test_graph_utils/test_edge.py
  tests/test_graph_utils/test_node.py
  tests/test_json.py
  tests/test_search.py
Labels: breakingchange, redis-7

#1859 Add support for SINTERCARD
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#1849 Add support for BLMPOP
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#1871 Add redis5 and redis4 dockers
  .github/workflows/integration.yaml
  dev_requirements.txt
  docker/base/Dockerfile.cluster4
  docker/base/Dockerfile.cluster5
  docker/base/Dockerfile.redis4
  docker/base/Dockerfile.redis5
  docker/base/Dockerfile.sentinel4
  docker/base/Dockerfile.sentinel5
  docker/base/create_cluster.sh
  docker/base/create_cluster4.sh
  docker/base/create_cluster5.sh
  docker/redis4/master/redis.conf
  docker/redis4/sentinel/sentinel_1.conf
  docker/redis4/sentinel/sentinel_2.conf
  docker/redis4/sentinel/sentinel_3.conf
  docker/redis5/master/redis.conf
  docker/redis5/replica/redis.conf
  docker/redis5/sentinel/sentinel_1.conf
  docker/redis5/sentinel/sentinel_2.conf
  docker/redis5/sentinel/sentinel_3.conf
  docker/redis6.2/master/redis.conf
  docker/redis6.2/replica/redis.conf
  docker/redis6.2/sentinel/sentinel_1.conf
  docker/redis6.2/sentinel/sentinel_2.conf
  docker/redis6.2/sentinel/sentinel_3.conf
  docker/stunnel/README
  docker/stunnel/keys/ca-cert.pem
  docker/stunnel/keys/ca-key.pem
  docker/stunnel/keys/client-cert.pem
  docker/stunnel/keys/client-key.pem
  docker/stunnel/keys/client-req.pem
  docker/stunnel/keys/server-cert.pem
  docker/stunnel/keys/server-key.pem
  docker/stunnel/keys/server-req.pem
  tasks.py
  tox.ini
Labels: chore

#1917 Add type hints for list commands
  redis/commands/core.py
Labels: feature

#1919 Add type hints for hash commands
  redis/commands/core.py
Labels: feature

#1918 Add type hints for set commands
  redis/commands/core.py
Labels: feature

#1923 Add support for ZMPOP
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#1921 Add type hints for JSON commands
  docs/examples/search_json_examples.ipynb
  redis/commands/json/_util.py
  redis/commands/json/commands.py
Labels: feature

#1916 Add set and get examples
  docs/examples.rst
  docs/examples/set_and_get_examples.ipynb
Labels: waiting-for-response

#1924 Add support for LCS
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#1926 Fix flushdb and flushall
  redis/cluster.py
  tests/test_cluster.py
Labels: bug

#1920 fix quantile test
  tests/test_search.py
Labels: bug

#1990 Delete update-changes workflow and edit PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/update-changes.yaml
Labels: chore

#1986 Vector similiary search support
  redis/commands/search/commands.py
  tests/test_search.py
Labels: feature

#1984 docs: fix the wrong link to watch command
  redis/commands/core.py
Labels: chore

#1936 Fix typo in readme
  README.md
Labels: chore

#1988 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
  CHANGES
Labels: chore

#1993 Adding ExecutionPlan support for graph
  redis/commands/graph/commands.py
  redis/commands/graph/execution_plan.py
  tests/test_graph.py
Labels: feature

#1992 Add support for ACL DRYRUN
  redis/commands/core.py
  tests/test_commands.py
Labels: feature, redis-7

#1997 Fixing type annotation for EXPLAIN
  redis/commands/search/commands.py
Labels: chore

#1995 Ensuring CI runs against integration branches
  .github/workflows/integration.yaml
Labels: chore

#1985 FixingElevated CPU utilization on one node when using RedisCluster pipeline
  redis/cluster.py
Labels: bug

#1998 Add support for Redis 7 functions
  redis/client.py
  redis/commands/core.py
  redis/connection.py
  tests/conftest.py
  tests/test_commands.py
  tests/test_function.py
  tests/test_scripting.py
Labels: feature, redis-7

#2001 Catch OSError in BlockingConnectionPool.get_connection
  redis/connection.py
Labels: bug

#1937 Add cluster support for scripting
  README.md
  redis/cluster.py
  redis/commands/cluster.py
  redis/commands/core.py
  redis/commands/parser.py
  redis/utils.py
  tests/test_command_parser.py
  tests/test_scripting.py
Labels: feature

#2008 Add Python 3.6 back to hash verify CI
  .github/workflows/integration.yaml
Labels: chore

#2015 Renaming chore as maintenance
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter-config.yml
Labels: chore

#2009 Add AsyncFunctionCommands
  redis/commands/core.py
Labels: maintenance
