Repository redis/redis-py, pull requests merged in 2023-05, with the labels that each got.

#2729 Fix `ClusterCommandProtocol` not itself being marked as a protocol
  CHANGES
  redis/typing.py
Labels: maintenance

#2719 Fix potential race condition during disconnection
  redis/connection.py
Labels: bug

#2726 add "address_remap" feature to RedisCluster
  CHANGES
  redis/asyncio/cluster.py
  redis/cluster.py
  tests/test_asyncio/test_cluster.py
  tests/test_cluster.py
Labels: feature

#2736 Update CONTRIBUTING guidelines
  CONTRIBUTING.md
Labels: maintenance

#2740 Fix `COMMAND` response in resp3 (redis 7+)
  redis/client.py
  redis/parsers/resp3.py
Labels: bug

#2737 Fix protocol version checking
  redis/asyncio/client.py
  redis/client.py
  tests/conftest.py
Labels: bug

#2743 Version 5.0.0b3
  setup.py
Labels: maintenance

#2748 Fixing CI
  dev_requirements.txt
Labels: maintenance

#2706 Add RedisCluster.remap_host_port, Update tests for CWE 404
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_cwe_404.py
  tests/test_asyncio/test_sentinel.py
  tests/test_cluster.py
Labels: maintenance, async

#2747 Typo in docs
  docs/redismodules.rst
Labels: maintenance

#2704 Add support for cluster myshardid
  redis/cluster.py
  redis/commands/cluster.py
  tests/test_asyncio/test_cluster.py
  tests/test_cluster.py
Labels: feature

#2732 Fix slowlog_get() return value
  redis/client.py
  tests/test_commands.py
Labels: bug

#2695 Optionally disable disconnects in read_response
  CHANGES
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/connection.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_cwe_404.py
  tests/test_commands.py
  tests/test_connection.py
Labels: bug

#2745 Add client no-touch
  redis/commands/core.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: feature

#2752 Fix create single connection client from url
  redis/asyncio/client.py
  redis/client.py
  tests/test_asyncio/test_connection.py
  tests/test_connection.py
Labels: bug

#2739 Fix `xadd` allow non negative maxlen
  CHANGES
  redis/commands/core.py
Labels: bug

#2761 support JSON.MERGE Command
  redis/commands/json/__init__.py
  redis/commands/json/commands.py
  tests/test_asyncio/test_json.py
  tests/test_json.py
Labels: feature, experimental

#2757 Fix parse resp3 dict response: don't use dict comprehension
  dev_requirements.txt
  redis/parsers/resp3.py
Labels: bug

#2755 Issue #2749: Remove unnecessary __del__ handlers
  CHANGES
  redis/asyncio/connection.py
Labels: bug

#2758 Add WITHSCORE to ZRANK
  redis/commands/core.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: feature
