Repository redis/redis-py, pull requests merged in 2023-11, with the labels that each got.

#2984 Fix BlockingConnectionPool.from_url parsing of timeout in query args #2983
  redis/asyncio/connection.py
  redis/connection.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_connection_pool.py
Labels: bug

#2982 Fix parsing resp3 dicts
  redis/_parsers/resp3.py
Labels: bug

#3038 Client Side Caching: Alpha support
  redis/__init__.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/sentinel.py
  redis/cache.py
  redis/client.py
  redis/cluster.py
  redis/commands/cluster.py
  redis/commands/core.py
  redis/commands/json/commands.py
  redis/commands/timeseries/commands.py
  redis/commands/timeseries/utils.py
  redis/sentinel.py
  redis/typing.py
Labels: feature, experimental

#3044 Version 5.1.0a1
  setup.py
Labels: skip-changelog

#3022 Fixed typo in ocsp.py
  redis/ocsp.py
Labels: maintenance
