Repository redis/redis-py, pull requests merged in 2023-01, with the labels that each got.

#2537 Add dialect to ft aggregate
  redis/commands/search/aggregation.py
  tests/test_asyncio/test_search.py
  tests/test_search.py
Labels: feature

#2535 Including startup instructions via redis-stack docker
  README.md
Labels: maintenance

#2539 Fix AttributeError when trying to split library version
  redis/__init__.py
Labels: maintenance

#2530 Remove `DeprecationWarning` by replace `get_event_loop` with `get_running_loop`
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/asyncio/lock.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_lock.py
  tests/test_asyncio/test_pubsub.py
Labels: maintenance

#2534 Fix incorrect _disconnect_raise docstring
  redis/asyncio/client.py
Labels: maintenance

#2542 ValueError must be AttributeError in __init__.py
  redis/__init__.py
Labels: maintenance

#2531 Add type checking to `__eq__` in graph classes
  redis/commands/graph/edge.py
  redis/commands/graph/node.py
  redis/commands/graph/path.py
Labels: bug

#2544 Version 4.4.1
  setup.py
Labels: maintenance

#2549 Allow replica to master promotion in nodes_cache
  redis/cluster.py
  tests/test_cluster.py
Labels: bug

#2547 add support for custom connection pool class in NodesManager
  redis/cluster.py
  tests/test_cluster.py
Labels: feature

#2545 Add support to BF.CARD
  redis/commands/bf/__init__.py
  redis/commands/bf/commands.py
  tests/test_asyncio/test_bloom.py
  tests/test_bloom.py
Labels: feature, experimental

#2556 Change redismod docker to redis-stack-server
  tox.ini
Labels: maintenance

#2553 Fix: add missing `Union` type in method `StreamCommands.xclaim()`
  redis/commands/core.py
Labels: maintenance

#2543 Simplify the sync SocketBuffer, add type hints
  CHANGES
  redis/connection.py
Labels: maintenance

#2566 trivial typo fix
  docs/advanced_features.rst
  docs/examples/pipeline_examples.ipynb
Labels: maintenance

#2562 Add support for `unlink` in cluster pipeline
  CHANGES
  redis/cluster.py
  tests/test_cluster.py
Labels: feature

#2568 Fix issue 2540: Synchronise concurrent command calls to single-client to single-client mode
  redis/asyncio/client.py
  tests/test_asyncio/test_connection.py
Labels: bug, async
