Repository redis/redis-py, pull requests merged in 2023-02, with the labels that each got.

#2573 Fix: tuple function cannot be passed more than one argument
  redis/__init__.py
Labels: bug

#2570 Use hiredis::pack_command to serialized the commands.
  CHANGES
  redis/connection.py
  redis/utils.py
  tests/test_encoding.py
Labels: feature

#2569 Fix issue 2567: NoneType check before raising exception
  redis/connection.py
Labels: bug

#2557 Fix issue 2349: Let async HiredisParser finish parsing after a Connection.disconnect()
  CHANGES
  redis/asyncio/connection.py
  tests/test_asyncio/test_connection.py
Labels: bug

#2507 Add TS.MGET example for OS Redis Cluster
  docs/examples/timeseries_examples.ipynb
Labels: maintenance, experimental

#2416 Fix issue with `pack_commands` returning an empty byte sequence
  redis/asyncio/connection.py
  redis/connection.py
Labels: bug

#2590 Fix for `lpop` and `rpop` return typing
  redis/commands/core.py
Labels: maintenance

#2584 Update README to make pip install copy-pastable on zsh
  README.md
Labels: maintenance
