Repository redis/redis-py, pull requests merged in 2023-08, with the labels that each got.

#2869 Fixing doc builds
  .github/workflows/docs.yaml
  docs/conf.py
  docs/examples/redis-stream-example.ipynb
  docs/requirements.txt
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/commands/core.py
  tasks.py
Labels: maintenance

#2863 RESP3 connection examples
  README.md
  docs/examples/asyncio_examples.ipynb
  docs/examples/connection_examples.ipynb
Labels: maintenance

#2852 Python 3.7 EOL
  README.md
Labels: maintenance, breakingchange

#2848 Fix a duplicate word in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: maintenance

#2850 Add sync modules (except search) tests to cluster CI
  redis/commands/bf/__init__.py
  redis/commands/helpers.py
  redis/commands/json/__init__.py
  redis/commands/timeseries/__init__.py
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_json.py
  tests/test_bloom.py
  tests/test_graph.py
  tests/test_json.py
  tests/test_timeseries.py
Labels: maintenance

#2812 Fix timeout retrying on pipeline execution
  redis/client.py
Labels: bug, ready-for-merge

#2817 Fix type hints in SearchCommands
  redis/commands/search/commands.py
Labels: maintenance, ready-for-merge

#2738 Add py.typed in accordance with PEP-561
  CHANGES
  redis/py.typed
  setup.py
Labels: maintenance, waiting-for-response

#2875 [4.6.1] Supporting setting CLIENT INFO via CLIENT SETINFO
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/commands/core.py
  redis/connection.py
  redis/utils.py
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connection.py
  tests/test_commands.py
  tests/test_search.py
Labels: feature

#2872 RESP 3 feature documentation
  .github/spellcheck-settings.yml
  .github/wordlist.txt
  .github/workflows/spellcheck.yml
  README.md
  docs/advanced_features.rst
  docs/clustering.rst
  docs/examples/asyncio_examples.ipynb
  docs/examples/connection_examples.ipynb
  docs/index.rst
  docs/lua_scripting.rst
  docs/resp3_features.rst
Labels: maintenance

#2861 Adding support for triggered functions (TFUNCTION)
  dockers/cluster.redis.conf
  redis/cluster.py
  redis/commands/cluster.py
  redis/commands/core.py
  tests/test_cluster.py
  tests/test_commands.py
Labels: feature

#2874 Version 5.0.0
  setup.py
Labels: maintenance

#2884 Updating client license to clear, MIT
  LICENSE
Labels: maintenance

#2902 Fix redis 7.2.0 tests
  redis/cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: maintenance

#2900 Fix: automatically close connection pool for async Sentinel
  redis/asyncio/sentinel.py
  tests/test_asyncio/test_sentinel.py
Labels: bug

#2894 Fix: SentinelManagedConnection.read_response() got an unexpected keyword argument 'push_request'
  redis/sentinel.py
Labels: bug

#2920 Fix test_scorer (search)
  tests/test_asyncio/test_search.py
  tests/test_search.py
Labels: maintenance
