Repository redis/redis-py, pull requests merged in 2023-12, with the labels that each got.

#3042 Use `disable_decoding` in async `read_response` with hiredis parser.
  CHANGES
  redis/_parsers/hiredis.py
Labels: bug

#3027 Add "sum" to DUPLICATE_POLICY documentation of TS.CREATE, TS.ADD and TS.ALTER
  CHANGES
  redis/commands/timeseries/commands.py
Labels: maintenance

#3019 Typo in advanced features documentation
  docs/advanced_features.rst
Labels: maintenance

#3063 Fix parsing of `FT.PROFILE` result
  redis/commands/helpers.py
  tests/test_helpers.py
Labels: bug

#3068 Prevent async ClusterPipeline instances from becoming "false-y" in ca…
  CHANGES
  redis/asyncio/cluster.py
  tests/test_asyncio/test_pipeline.py
Labels: bug, breakingchange

#3001 Update repr of important classes with module name and recommended "< …
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/asyncio/sentinel.py
  redis/client.py
  redis/connection.py
  redis/sentinel.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_connection_pool.py
Labels: maintenance, breakingchange

#2980 Make the connection callback methods public again, add documentation
  CHANGES
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
Labels: maintenance

#2968 Update reported version deprecation in asyncio.client
  redis/asyncio/client.py
Labels: maintenance

#3012 Allow the parsing of the asking command to forward original options
  redis/_parsers/helpers.py
Labels: bug

#3069 unused example ID causes entire file to be shown
  doctests/dt_stream.py
Labels: maintenance

#3072 Fix Specifying Target Nodes broken hyperlink
  docs/clustering.rst
Labels: maintenance

#3071 Fix return types in json commands
  CHANGES
  redis/commands/json/commands.py
Labels: maintenance
