Repository redis/redis-py, pull requests merged in 2023-06, with the labels that each got.

#2780 RESP3 tests
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
  redis/parsers/__init__.py
  redis/parsers/resp3.py
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_pipeline.py
  tests/test_asyncio/test_pubsub.py
  tests/test_cluster.py
  tests/test_commands.py
  tests/test_function.py
  tests/test_pubsub.py
Labels: maintenance

#2799 Fix sharded pubsub threads issue
  redis/asyncio/connection.py
  redis/connection.py
Labels: bug

#2786 Fix JSON.MERGE Summary
  redis/commands/json/commands.py
Labels: maintenance, ready-for-merge

#2803 RESP3 modules support
  redis/commands/bf/__init__.py
  redis/commands/bf/commands.py
  redis/commands/bf/info.py
  redis/commands/json/__init__.py
  redis/commands/search/__init__.py
  redis/commands/search/commands.py
  redis/commands/timeseries/__init__.py
  redis/commands/timeseries/info.py
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_search.py
  tests/test_asyncio/test_timeseries.py
  tests/test_bloom.py
  tests/test_json.py
  tests/test_search.py
  tests/test_timeseries.py
Labels: feature

#2806 RESP3 fix async tests
  redis/client.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
  tests/test_credentials.py
Labels: maintenance

#2788 Fix Key Error in parse_xinfo_stream
  CHANGES
  redis/client.py
Labels: bug, ready-for-merge

#2796 Docstring formatting fix
  redis/exceptions.py
Labels: maintenance, ready-for-merge

#2778 Introduce OutOfMemoryError exception for Redis write command rejections due to OOM errors
  redis/__init__.py
  redis/asyncio/__init__.py
  redis/asyncio/connection.py
  redis/connection.py
  redis/exceptions.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_connection_pool.py
Labels: feature, ready-for-merge

#2631 Add unit tests for the `connect` method of all Redis connection classes
  tests/ssl_utils.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connect.py
  tests/test_connect.py
  tests/test_ssl.py
Labels: maintenance, ready-for-merge

#2771 Fix dead weakref in sentinel connection causing ReferenceError (#2767)
  CHANGES
  redis/sentinel.py
  tests/test_sentinel.py
Labels: bug, ready-for-merge

#2760 Add waitaof
  redis/cluster.py
  redis/commands/core.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: feature, ready-for-merge

#2734 Extract abstract async connection class
  redis/asyncio/connection.py
  redis/connection.py
Labels: feature, ready-for-merge

#2804 Fix type hint for retry_on_error in async cluster
  CHANGES
  redis/asyncio/cluster.py
Labels: maintenance, ready-for-merge

#2809 Fix CI
  redis/asyncio/connection.py
  tests/test_asyncio/test_graph.py
  tests/test_graph.py
Labels: maintenance

#2766 Support JSON.MSET Command
  redis/commands/json/__init__.py
  redis/commands/json/commands.py
  tests/test_asyncio/test_json.py
  tests/test_json.py
Labels: feature, docs-review

#2810 Version 4.6.0
  setup.py
Labels: maintenance, skip-changelog

#2813 Change `SISMEMBER` return type to int
  redis/client.py
  redis/commands/core.py
Labels: breakingchange
