Repository redis/redis-py, pull requests merged in 2023-09, with the labels that each got.

#2927 Deprecate RedisGraph
  redis/commands/graph/__init__.py
Labels: maintenance

#2923 Fix protocol checking for search commands
  redis/commands/search/commands.py
Labels: bug

#2918 Fix typo in redis-stream-example.ipynb
  docs/examples/redis-stream-example.ipynb
Labels: maintenance

#2899 Fix resource warnings in unit tests
  tests/test_asyncio/test_connect.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_cwe_404.py
Labels: maintenance

#2896 Add 7.2 to supported Redis versions
  README.md
Labels: maintenance

#2922 Fix async sentinel: add `push_request` keyword argument to `read_response`
  redis/asyncio/sentinel.py
Labels: bug

#2929 Remove mentions of Tox
  .dockerignore
  .flake8
  .github/PULL_REQUEST_TEMPLATE.md
  .github/wordlist.txt
  .gitignore
  CONTRIBUTING.md
  dev_requirements.txt
Labels: maintenance

#2934 Support timeout = 0 in search query
  redis/commands/search/query.py
  tests/test_search.py
Labels: bug

#2936 Fix resource usage and cleanup Mocks in the unit tests
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_cwe_404.py
  tests/test_connect.py
Labels: maintenance

#2932 Avoid creating ref cycles
  redis/connection.py
Labels: maintenance

#2890 add pagination, sorting and grouping examples to search json example
  docs/examples/search_json_examples.ipynb
Labels: maintenance

#2919 Cluster determine slot command name need upper
  redis/asyncio/cluster.py
  redis/cluster.py
Labels: bug

#2913 Add `Redis.from_pool()` class method, for explicitly owning and closing a ConnectionPool
  docs/examples/asyncio_examples.ipynb
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/asyncio/sentinel.py
  redis/client.py
  redis/sentinel.py
  tests/test_asyncio/test_connection.py
  tests/test_connection.py
  tests/test_sentinel.py
Labels: feature

#2949 Add support for multiple values in `RPUSHX`
  redis/commands/core.py
Labels: feature

#2950 Fixing monitor parsing for messages containing specific substrings
  redis/asyncio/client.py
  redis/client.py
Labels: bug

#2951 Add support for `ModuleCommands` in cluster
  redis/cluster.py
  redis/commands/cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: feature

#2898 Provide aclose() / close() for classes requiring lifetime management
  CHANGES
  docs/examples/asyncio_examples.ipynb
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/connection.py
  tests/test_asyncio/compat.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_pipeline.py
  tests/test_asyncio/test_pubsub.py
  tests/test_connection_pool.py
  tests/test_pipeline.py
Labels: feature

#2870 async fixes, remove __del__ and other things
  redis/_parsers/base.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
  tests/test_asyncio/test_sentinel_managed_connection.py
Labels: maintenance

#2955 Replace `clear_connect_callbacks` with `_deregister_connect_callback`
  redis/asyncio/client.py
Labels: maintenance

#2816 Save a reference to created async tasks, to avoid tasks potentially disappearing
  redis/asyncio/cluster.py
Labels: maintenance

#2952 Type hint improvements
  redis/_parsers/base.py
  redis/_parsers/resp3.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/commands/core.py
  redis/commands/json/commands.py
  redis/commands/search/__init__.py
  redis/commands/search/aggregation.py
  redis/commands/search/commands.py
  redis/commands/search/field.py
  redis/commands/search/query.py
  redis/commands/search/reducers.py
  redis/commands/search/result.py
  redis/commands/search/suggestion.py
  redis/connection.py
  tests/test_asyncio/test_cwe_404.py
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_lock.py
  tests/test_asyncio/test_pipeline.py
  tests/test_asyncio/test_pubsub.py
  tests/test_asyncio/test_search.py
  tests/test_asyncio/test_sentinel.py
  tests/test_asyncio/test_timeseries.py
  tests/test_commands.py
  tests/test_graph_utils/test_edge.py
  tests/test_json.py
  tests/test_lock.py
  tests/test_pipeline.py
  tests/test_pubsub.py
  tests/test_search.py
  tests/test_timeseries.py
Labels: maintenance

#2958 Version 5.0.1
  setup.py
Labels: maintenance, skip-changelog
