Repository redis/redis-py, pull requests merged in 2023-04, with the labels that each got.

#2699 Really do not use asyncio's timeout lib before 3.11.2
  setup.py
Labels: bug, async

#2694 Fix memory leak caused by hiredis in asyncio case
  CHANGES
  redis/asyncio/connection.py
  redis/connection.py
Labels: bug, async

#2703 Update example of Redisearch creating index
  docs/redismodules.rst
Labels: maintenance, update-docs

#2661 Improving Vector Similarity Search Example
  docs/examples/search_vector_similarity_examples.ipynb
Labels: maintenance

#2721 Add support for PubSub with RESP3 parser
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/client.py
  redis/connection.py
  redis/parsers/resp3.py
  redis/utils.py
  tests/test_asyncio/test_pubsub.py
  tests/test_pubsub.py
Labels: feature

#2723 5.0.0b2
  setup.py
Labels: maintenance, skip-changelog

#2718 Fix incorrect usage of once flag in async Sentinel
  CHANGES
  redis/asyncio/sentinel.py
Labels: bug

#2628 return response in case of KeyError
  redis/client.py
  tests/test_commands.py
Labels: bug

#2725 Add WITHSCORES to ZREVRANK Command
  redis/commands/core.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: feature
