Repository redis/redis-py, pull requests merged in 2023-10, with the labels that each got.

#2963 Fixing type hint on from_url
  redis/client.py
Labels: maintenance

#2997 Fix incorrect lock scope in BlockingConnectionPool
  redis/asyncio/connection.py
Labels: bug

#3005 Close various objects created during asyncio tests
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connect.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_cwe_404.py
  tests/test_asyncio/test_retry.py
  tests/test_asyncio/test_sentinel.py
  tests/test_asyncio/test_sentinel_managed_connection.py
Labels: maintenance

#3006 Linking to Redis learning resources
  README.md
Labels: maintenance

#2957 Add GEOSHAPE field type for index creation of RediSearch
  redis/commands/search/field.py
  tests/test_search.py
Labels: feature

#2999 Better deal with "lost" connections for async Redis
  redis/asyncio/client.py
  redis/asyncio/connection.py
  tests/test_asyncio/test_connection.py
Labels: maintenance

#2977 Update client.py sleep_time typing for run_in_thread function
  redis/client.py
Labels: maintenance
