Repository redis/redis-py, pull requests merged in 2023-03, with the labels that each got.

#2611 update json().arrindex() default values
  redis/commands/json/commands.py
  tests/test_asyncio/test_json.py
  tests/test_json.py
Labels: bug, RedisJSON

#2596 Speeding up the protocol parsing
  redis/asyncio/connection.py
  redis/connection.py
Labels: feature

#2587 Fixed CredentialsProvider examples
  docs/examples/connection_examples.ipynb
Labels: maintenance

#2605 [docs] ConnectionPool SSL example
  docs/examples/ssl_connection_examples.ipynb
Labels: maintenance

#2617 [types] update return type of smismember to list[int]
  redis/commands/core.py
Labels: maintenance

#2615 Making search document subscriptable
  redis/commands/search/document.py
  tests/test_search.py
Labels: feature

#2620 Remove redundant assignment to RedisCluster.nodes_manager.
  redis/cluster.py
Labels: maintenance

#2602 fix: replace async_timeout by asyncio.timeout
  CHANGES
  redis/asyncio/connection.py
  setup.py
  tests/test_asyncio/test_pubsub.py
Labels: bug

#2577 add queue_class to REDIS_ALLOWED_KEYS
  redis/cluster.py
  tests/test_cluster.py
Labels: feature

#2608 Coverage for pypy-3.9
  .github/workflows/integration.yaml
Labels: maintenance

#2582 Fix behaviour of async PythonParser to match RedisParser as for issue #2349
  CHANGES
  redis/asyncio/connection.py
  tests/test_asyncio/test_connection.py
Labels: bug

#2627 Version 4.5.2
  setup.py
Labels: skip-changelog

#2641 AsyncIO Race Condition Fix
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  setup.py
  tests/asynctests
  tests/synctests
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connection.py
Labels: bug

#2640 AsyncIO Race Condition Fix
  .github/workflows/integration.yaml
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  setup.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connection.py
Labels: bug

#2574 Reorganizing the parsers code, and add support for RESP3
  .github/workflows/integration.yaml
  benchmarks/socket_read_size.py
  redis/asyncio/__init__.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/asyncio/parser.py
  redis/client.py
  redis/cluster.py
  redis/commands/__init__.py
  redis/connection.py
  redis/parsers/__init__.py
  redis/parsers/base.py
  redis/parsers/commands.py
  redis/parsers/encoders.py
  redis/parsers/hiredis.py
  redis/parsers/resp2.py
  redis/parsers/resp3.py
  redis/parsers/socket.py
  redis/typing.py
  redis/utils.py
  setup.py
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_pubsub.py
  tests/test_cluster.py
  tests/test_command_parser.py
  tests/test_commands.py
  tests/test_connection.py
  tests/test_connection_pool.py
  tests/test_pipeline.py
  tests/test_pubsub.py
  whitelist.py
Labels: feature, breakingchange

#2659 fix: do not use asyncio's timeout lib before 3.11.2
  redis/asyncio/connection.py
  setup.py
  tests/test_asyncio/test_pubsub.py
Labels: bug, async

#2642 Removing accidentally checked in files
  tests/asynctests
  tests/synctests
Labels: maintenance

#2666 Fixing cancelled async futures
  .github/workflows/integration.yaml
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_cwe_404.py
  tests/test_asyncio/test_pubsub.py
Labels: bug, experimental

#2674 Version 4.5.4
  setup.py
Labels: skip-changelog

#2671 Version 4.4.4
  .github/workflows/integration.yaml
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  setup.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connection.py
  tests/test_asyncio/test_cwe_404.py
  tests/test_asyncio/test_pubsub.py
Labels: skip-changelog
