Repository redis/redis-py, pull requests merged in 2024-07, with the labels that each got.

#3305 Format connection errors in the same way everywhere
  redis/asyncio/connection.py
  redis/connection.py
  redis/utils.py
  tests/test_asyncio/test_connection.py
  tests/test_connection.py
Labels: maintenance

#3309 Decode search results at field level
  dev_requirements.txt
  docs/examples/search_vector_similarity_examples.ipynb
  redis/commands/search/_util.py
  redis/commands/search/commands.py
  redis/commands/search/query.py
  redis/commands/search/result.py
  tests/test_asyncio/test_search.py
  tests/test_search.py
Labels: bug

#2979 Python 3.12
  .flake8
  .github/workflows/integration.yaml
  .gitignore
  dev_requirements.txt
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/cluster.py
  redis/commands/graph/query_result.py
  redis/connection.py
  requirements.txt
  setup.py
  tasks.py
  tests/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connect.py
  tests/test_asyncio/test_cwe_404.py
  tests/test_asyncio/test_lock.py
  tests/test_asyncio/test_search.py
  tests/test_connect.py
Labels: maintenance

#3315 Close Unix sockets if the connection attempt fails
  CHANGES
  redis/connection.py
Labels: maintenance

#3316 Suppress `Graph` deprecation warning in test suite
  pytest.ini
  tasks.py
  tests/test_graph.py
Labels: maintenance

#3318 Close SSL sockets when connections/validations fail
  CHANGES
  redis/connection.py
Labels: maintenance

#3323 Upgrade Flake8
  dev_requirements.txt
  redis/_parsers/helpers.py
  redis/commands/core.py
  redis/commands/timeseries/info.py
  redis/typing.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_asyncio/test_lock.py
  tests/test_json.py
  tests/test_lock.py
Labels: maintenance

#3324 Handle RESP3 sets as Python lists
  doctests/dt_set.py
  redis/_parsers/helpers.py
  redis/_parsers/resp3.py
  redis/commands/bf/commands.py
  redis/utils.py
  setup.py
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_search.py
  tests/test_asyncio/test_timeseries.py
  tests/test_bloom.py
  tests/test_cluster.py
  tests/test_command_parser.py
  tests/test_commands.py
  tests/test_function.py
  tests/test_search.py
  tests/test_timeseries.py
Labels: bug, breakingchange
