Repository redis/redis-py, pull requests merged in 2024-01, with the labels that each got.

#3089 Client side caching invalidations (standalone)
  redis/__init__.py
  redis/_parsers/resp3.py
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/cache.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
  tests/test_asyncio/test_cache.py
  tests/test_cache.py
Labels: feature, experimental

#3062 Fix `acl_genpass` with bits
  redis/commands/core.py
  tests/test_commands.py
Labels: bug

#2928 Partial clean up of Python 3.7 compatibility
  .github/workflows/integration.yaml
  redis/_parsers/hiredis.py
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/commands/cluster.py
  redis/commands/core.py
  redis/compat.py
  redis/typing.py
  setup.py
Labels: maintenance, breakingchange

#3093 Version 5.1.0b1
  setup.py
Labels: skip-changelog

#3099 Support client side caching with ConnectionPool
  redis/_cache.py
  redis/asyncio/client.py
  redis/asyncio/connection.py
  redis/client.py
  redis/connection.py
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cache.py
  tests/test_asyncio/test_connection.py
  tests/test_cache.py
Labels: feature, experimental

#3100 Version 5.1.0b2
  setup.py
Labels: skip-changelog

#3102 Support client side caching with RedisCluster
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/cluster.py
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cache.py
  tests/test_asyncio/test_cluster.py
  tests/test_cache.py
  tests/test_cluster.py
Labels: feature, experimental

#3101 Always submitting codecov
  .github/workflows/integration.yaml
Labels: maintenance

#3036 [main/master] filter commits for main branch
  .github/release-drafter-config.yml
Labels: maintenance

#3073 fix(docs): organize cluster mode part of lua scripting
  docs/lua_scripting.rst
Labels: maintenance

#3029 Fix typing of `HashCommand.hdel`
  redis/commands/core.py
Labels: maintenance

#3023 Adding lock_name to LockError
  CHANGES
  redis/exceptions.py
  redis/lock.py
  tests/test_lock.py
Labels: feature

#2908 Fix type hint of arbitrary argument lists
  redis/commands/core.py
Labels: maintenance

#3103 Fix: `HSET` unexpectedly mutates the list passed to items
  redis/commands/core.py
Labels: bug

#3106 Return a copy of the response from cache
  redis/_cache.py
  tests/test_asyncio/test_cache.py
  tests/test_cache.py
Labels: bug

#3104 Fix possible pipeline connections leak
  redis/cluster.py
Labels: bug

#3110 CSC Review Fixes - expose delete functions, rename attribute names, add AbstractCache class
  redis/_cache.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
Labels: feature, experimental

#3109 Updating async-timeout to 4.0.3
  setup.py
Labels: maintenance

#3112 Version 5.1.0b3
  setup.py
Labels: skip-changelog

#3115 Add modules support to async RedisCluster
  redis/commands/cluster.py
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_graph.py
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_timeseries.py
Labels: feature

#3120 Fix grammer in BlockingConnectionPool class documentation
  redis/asyncio/connection.py
Labels: maintenance
