Repository redis/redis-py, pull requests merged in 2024-02, with the labels that each got.

#3133 release already acquired connections on ClusterPipeline, when get_connection raises an exception
  redis/cluster.py
  tests/test_cluster.py
Labels: bug

#3127 Allow to control the minimum SSL version
  CHANGES
  docs/examples/ssl_connection_examples.ipynb
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/connection.py
  tests/test_asyncio/test_connect.py
  tests/test_connect.py
Labels: feature

#3129 docs: Add timeout parameter for get_message example
  docs/examples/asyncio_examples.ipynb
Labels: maintenance

#3142 Revert stale issue version update
  .github/workflows/stale-issues.yml
Labels: maintenance

#3149 Ignore TypeError on disconnect (within multiprocess)
  redis/connection.py
Labels: bug

#3146 Remove typing-extensions from deps
  requirements.txt
  setup.py
Labels: maintenance

#3134 Fix retry logic for pubsub and pipeline
  redis/asyncio/client.py
  redis/client.py
Labels: bug

#3004 Fix incorrect asserts in test and ensure connections are closed
  tests/test_ssl.py
Labels: maintenance

#3160 Fix bug: client side caching causes unexpected disconnections
  redis/_parsers/resp3.py
  redis/client.py
  redis/commands/core.py
  redis/connection.py
  tests/test_cache.py
Labels: bug

#3165 Fix bug: client side caching causes unexpected disconnections (async version)
  redis/_parsers/base.py
  redis/_parsers/resp3.py
  redis/asyncio/client.py
  redis/asyncio/connection.py
  tests/test_asyncio/test_cache.py
Labels: bug
