Repository redis/redis-py, pull requests merged in 2024-06, with the labels that each got.

#3264 Fix parsing of INFO response
  redis/_parsers/helpers.py
  tests/test_parsers/test_helpers.py
Labels: bug

#3246 Use standard Redis docker image in CI
  docker-compose.yml
  dockers/Dockerfile.cluster
  dockers/cluster.redis.conf
  dockers/create_cluster.sh
  tasks.py
  tests/conftest.py
  tests/test_asyncio/test_bloom.py
  tests/test_asyncio/test_graph.py
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_search.py
  tests/test_asyncio/test_timeseries.py
  tests/test_bloom.py
  tests/test_cluster.py
  tests/test_commands.py
  tests/test_graph.py
  tests/test_json.py
  tests/test_search.py
  tests/test_timeseries.py
Labels: maintenance

#3218 Hash field expiration commands
  redis/commands/core.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_graph.py
  tests/test_asyncio/test_hash.py
  tests/test_cluster.py
  tests/test_commands.py
  tests/test_graph.py
  tests/test_hash.py
Labels: feature

#3228 Timeseries insertion filters for close samples
  .github/workflows/integration.yaml
  docker-compose.yml
  redis/commands/timeseries/commands.py
  tests/conftest.py
  tests/test_asyncio/test_timeseries.py
  tests/test_timeseries.py
Labels: feature, breakingchange

#3244 Add extra tests for GEO search
  tests/test_search.py
Labels: maintenance

#3231 Support missing/empty/null values in search
  redis/commands/search/commands.py
  redis/commands/search/field.py
  tests/test_search.py
Labels: feature

#3276 Test special characters escaping in search
  tests/test_search.py
Labels: maintenance

#3277 Handle lists in the response of INFO
  .github/workflows/docs.yaml
  .github/workflows/integration.yaml
  dockers/cluster.redis.conf
  redis/_parsers/helpers.py
  redis/commands/helpers.py
  setup.py
  tasks.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_graph.py
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_timeseries.py
  tests/test_cluster.py
  tests/test_commands.py
  tests/test_graph.py
  tests/test_json.py
  tests/test_parsers/test_helpers.py
  tests/test_timeseries.py
Labels: bug

#3278 Handle lists in the response of INFO
  redis/_parsers/helpers.py
  tests/test_parsers/test_helpers.py
Labels: bug

#3270 Make sure the CI actually runs RESP3 tests
  .github/workflows/integration.yaml
  redis/_parsers/hiredis.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_json.py
  tests/test_asyncio/test_timeseries.py
  tests/test_command_parser.py
  tests/test_commands.py
  tests/test_json.py
  tests/test_timeseries.py
Labels: maintenance

#3285 Add CODECOV token to CI
  .github/workflows/integration.yaml
Labels: maintenance

#3287 Re-enable Graph tests
  .github/workflows/integration.yaml
  docker-compose.yml
  dockers/create_cluster.sh
  redis/_parsers/resp3.py
  tests/conftest.py
  tests/test_asyncio/test_graph.py
  tests/test_commands.py
  tests/test_graph.py
  tests/test_timeseries.py
Labels: maintenance

#3288 Version 5.1.0b7
  setup.py
Labels: skip-changelog

#3295 Updated version of redis-stack docker image
  docker-compose.yml
  dockers/Dockerfile.cluster
Labels: maintenance
