Repository redis/redis-py, pull requests merged in 2024-05, with the labels that each got.

#3216 Streamline client side caching API typing
  dev_requirements.txt
  dockers/sentinel.conf
  redis/_cache.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/cluster.py
  redis/connection.py
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cache.py
  tests/test_cache.py
Labels: bug, maintenance

#3214 Make it possible to customize SSL ciphers
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/connection.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connect.py
  tests/test_connect.py
  tests/test_ssl.py
Labels: bug

#3224 Version 5.1.0b5
  setup.py
Labels: skip-changelog

#3187 Support the MAXAGE option for CLIENT KILL
  redis/commands/core.py
  tests/test_commands.py
Labels: feature

#3157 Support NOVALUES parameter for HSCAN
  redis/_parsers/helpers.py
  redis/commands/core.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: feature

#3229 DOC-3787 add missing code samples for JSON
  doctests/dt_json.py
Labels: docs-review

#3188 Document XREAD of last message (+)
  docs/examples/redis-stream-example.ipynb
Labels: update-docs

#3232 Streamline documentation style
  .github/wordlist.txt
  CONTRIBUTING.md
  docs/conf.py
  redis/commands/core.py
Labels: update-docs

#3227 Update ResponseT type alias
  CHANGES
  redis/typing.py
Labels: maintenance

#3235 Fix typing for address_remap (fixes #3234)
  redis/asyncio/cluster.py
  redis/cluster.py
Labels: maintenance

#3236 Run pyupgrade for 3.8
  redis/__init__.py
  redis/client.py
  redis/cluster.py
  redis/commands/bf/__init__.py
  redis/commands/bf/info.py
  redis/commands/graph/__init__.py
  redis/commands/json/commands.py
  redis/utils.py
  tests/ssl_utils.py
  tests/test_asyncio/compat.py
  tests/test_asyncio/test_search.py
  tests/test_search.py
Labels: maintenance

#3245 Parse FT.PROFILE response more robustly
  redis/commands/helpers.py
Labels: maintenance

#3247 More robust parsing of memory stats response
  redis/_parsers/helpers.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: maintenance

#3249 Add missing type hints for `backoff.py`
  redis/backoff.py
Labels: maintenance
