Repository redis/redis-py, pull requests merged in 2024-03, with the labels that each got.

#3176 Make `message` in LockError optional to support backwards compatibility
  redis/exceptions.py
Labels: bug

#3177 Remove redundant async-timeout dependency from modern Python
  setup.py
Labels: maintenance

#3178 Cherry pick for v5.0.3
  .github/workflows/release-drafter.yml
  .github/workflows/spellcheck.yml
  redis/exceptions.py
  setup.py
Labels: maintenance

#3179 Version 5.0.3
  setup.py
Labels: maintenance, skip-changelog

#3158 Optimizing cluster initialization changing the checks for cluster-enabled flag
  redis/asyncio/cluster.py
  redis/cluster.py
  tests/test_asyncio/test_cluster.py
  tests/test_cluster.py
Labels: maintenance

#3125 Documentation update (asyncio_examples.ipynb)
  docs/examples/asyncio_examples.ipynb
Labels: maintenance

#3183 Avoid workflows canceling each other out
  .github/workflows/docs.yaml
  .github/workflows/integration.yaml
Labels: maintenance

#3193 Update black version to 24.3.0
  .flake8
  dev_requirements.txt
  redis/_parsers/helpers.py
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/asyncio/sentinel.py
  redis/cluster.py
  redis/commands/core.py
  redis/exceptions.py
  redis/sentinel.py
  redis/typing.py
  tests/test_asyncio/test_commands.py
Labels: maintenance
