Repository redis/redis-py, pull requests merged in 2025-03, with the labels that each got.

#3477 Fix connection health check for protocol != 2 when auth credentials are provided and health check interval is configured
  redis/asyncio/connection.py
  redis/connection.py
Labels: bug

#3147 Replace flake8+isort+black with `ruff`
  .flake8
  .isort.cfg
  benchmarks/basic_operations.py
  benchmarks/command_packer_benchmark.py
  benchmarks/socket_read_size.py
  dev_requirements.txt
  doctests/README.md
  pyproject.toml
  redis/_parsers/base.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/asyncio/utils.py
  redis/auth/token.py
  redis/client.py
  redis/cluster.py
  redis/commands/cluster.py
  redis/commands/core.py
  redis/commands/graph/commands.py
  redis/commands/helpers.py
  redis/connection.py
  redis/exceptions.py
  redis/ocsp.py
  redis/sentinel.py
  tasks.py
  tests/conftest.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_commands.py
  tests/test_asyncio/test_graph.py
  tests/test_asyncio/test_search.py
  tests/test_auth/test_token.py
  tests/test_cluster.py
  tests/test_commands.py
  tests/test_connection.py
  tests/test_graph.py
  tests/test_search.py
Labels: maintenance

#3544 (tests): Added testing for auth via DefaultAzureCredential
  dev_requirements.txt
  tests/entraid_utils.py
  tests/test_asyncio/conftest.py
  tests/test_asyncio/test_credentials.py
  tests/test_credentials.py
Labels: maintenance

#3548 Removing support for RedisGraph module.
  .github/wordlist.txt
  .github/workflows/install_and_test.sh
  CHANGES
  docker-compose.yml
  docs/redismodules.rst
  pyproject.toml
  redis/cluster.py
  redis/commands/graph/__init__.py
  redis/commands/graph/commands.py
  redis/commands/graph/edge.py
  redis/commands/graph/exceptions.py
  redis/commands/graph/execution_plan.py
  redis/commands/graph/node.py
  redis/commands/graph/path.py
  redis/commands/graph/query_result.py
  redis/commands/helpers.py
  redis/commands/redismodules.py
  tasks.py
  tests/test_asyncio/test_graph.py
  tests/test_graph.py
  tests/test_graph_utils/__init__.py
  tests/test_graph_utils/test_edge.py
  tests/test_graph_utils/test_node.py
  tests/test_graph_utils/test_path.py
  tests/test_helpers.py
Labels: breakingchange

#3485 DOC-4736 added geo indexing examples
  doctests/geo_index.py
Labels: docs-review

#3545 Fixing async cluster pipeline execution when client is created with cluster_error_retry_attempts=0
  redis/asyncio/cluster.py
  tests/test_asyncio/test_cluster.py
Labels: bug

#3556 Increasing the operations-per-run for stale issues GH action
  .github/workflows/stale-issues.yml
Labels: maintenance

#3567 Improvement: Use `shutdown()` Before `close()` in connection.py
  redis/connection.py
Labels: maintenance

#3576 Fix incorrect link to docs for fcall_ro command
  redis/commands/core.py
Labels: maintenance
