Repository redis/redis-py, pull requests merged in 2025-02, with the labels that each got.

#3494 Add types to `execute` method of pipelines
  redis/asyncio/client.py
  redis/client.py
  redis/cluster.py
Labels: techdebt

#3493 DOC-4796 fixed capped lists example
  doctests/dt_list.py
Labels: docs-review

#3499 Adding deprecation messages for the exposed in search module commands: FT.INFO, just for async client: FT.CONFIG GET and FT.CONFIG SET
  redis/commands/search/commands.py
Labels: maintenance

#3357 typing for client __init__
  redis/client.py
Labels: techdebt

#3354 Fixes minor grammar nit in documentation.
  docs/opentelemetry.rst
Labels: techdebt

#3507 Adding unit test for core info command related to modules info
  tests/test_commands.py
Labels: maintenance

#3505 Replacing the redis and redis-stack-server images with redis-libs-tests image in test infrastructure
  .github/actions/run-tests/action.yml
  .github/workflows/integration.yaml
  .gitignore
  docker-compose.yml
  setup.py
Labels: maintenance

#2930 Switch to PEP 517 packaging using hatchling
  .github/actions/run-tests/action.yml
  .github/workflows/docs.yaml
  .github/workflows/install_and_test.sh
  .github/workflows/integration.yaml
  .github/workflows/pypi-publish.yaml
  CONTRIBUTING.md
  INSTALL
  MANIFEST.in
  dev_requirements.txt
  docs/examples/opentelemetry/README.md
  pyproject.toml
  pytest.ini
  redis/__init__.py
  requirements.txt
  setup.py
  tasks.py
Labels: maintenance

#3527 Removing the requirements.txt from docs building dependencies
  .readthedocs.yml
  doctests/README.md
  doctests/requirements.txt
Labels: maintenance

#3528 Installing redis and its mandatory dependencies when building readthedocs artifacts
  .readthedocs.yml
Labels: maintenance

#3525 Adding vector search tests for types int8/uint8
  tests/test_search.py
Labels: maintenance

#3526 Fixing wrong type hints
  redis/commands/core.py
  redis/commands/search/commands.py
Labels: maintenance

#3537 Fixing typing for FCALL commands to match PEP 484
  redis/commands/core.py
Labels: breakingchange
