Repository redis/redis-py, pull requests merged in 2025-09, with the labels that each got.

#3761 Fix docstring for ssl_check_hostname
  redis/connection.py
Labels: maintenance

#3776 DOC-5743 BITOP examples
  doctests/dt_bitmap.py
Labels: docs-review

#3778 Renaming maintenance_events to maint_notifications part 2: renaming the files.
  redis/_parsers/base.py
  redis/client.py
  redis/connection.py
  redis/maint_notifications.py
  tests/test_maint_notifications.py
  tests/test_maint_notifications_handling.py
  tests/test_scenario/conftest.py
  tests/test_scenario/maint_notifications_helpers.py
  tests/test_scenario/test_maint_notifications.py
Labels: breakingchange

#3779 Adding 'auto' option to MaintNotificationsConfig.enabled
  redis/connection.py
  redis/maint_notifications.py
  tests/test_maint_notifications.py
  tests/test_maint_notifications_handling.py
Labels: maintenance
