Repository redis/redis-py, pull requests merged in 2025-07, with the labels that each got.

#3690 Add support for new BITOP operations: DIFF, DIFF1, ANDOR, ONE
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: maintenance

#3699 Update README.md - fix missing formatting for code example
  README.md
Labels: maintenance

#3688 Convert the value to int type only if it exists in CLIENT INFO
  redis/_parsers/helpers.py
Labels: maintenance

#3708 Fix compatibility with latest pytest-asyncio version(1.1.0)
  tests/test_asyncio/test_sentinel.py
  tests/test_cluster.py
Labels: maintenance

#3705 DOC-5424 time series examples
  doctests/dt_time_series.py
Labels: docs-review

#3668 add async Retry ``__eq__`` and ``__hash__`` & fix ExponentialWithJitterBackoff ``__eq__``
  redis/asyncio/retry.py
  redis/backoff.py
  redis/retry.py
  tests/test_retry.py
Labels: bug-fix
