Repository redis/redis-py, pull requests merged in 2025-05, with the labels that each got.

#3634 Fix `AttributeError` in `ClusterPipeline`
  redis/cluster.py
Labels: bug

#3610 Change type hints with possible None args or return types to be annotated with Optional - includes commands in core.py and json commands
  CHANGES
  redis/commands/core.py
  redis/commands/json/commands.py
Labels: maintenance

#3636 Allow newer PyJWT versions
  CHANGES
  pyproject.toml
Labels: maintenance

#3639 Updating Redis 8 test image for GH pipeline
  .github/workflows/integration.yaml
Labels: maintenance

#3633 Prevent RuntimeError while reinitializing clusters - sync and async
  redis/asyncio/cluster.py
  redis/cluster.py
Labels: bug

#3632 Adding return types for the RedisModuleCommands class
  redis/commands/redismodules.py
Labels: maintenance

#3617 Test against unstable hiredis-py
  .github/actions/run-tests/action.yml
  .github/workflows/hiredis-py-integration.yaml
Labels: maintenance

#3637 Fix SSL verification with ssl_cert_reqs="none" and ssl_check_hostname=True
  CHANGES
  docs/examples/ssl_connection_examples.ipynb
  redis/asyncio/connection.py
  redis/cluster.py
  redis/connection.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_ssl.py
  tests/test_ssl.py
Labels: bug, maintenance

#3644 Updating the readme and lib version to contain the changes from the latest stable release
  README.md
  docker-compose.yml
  redis/__init__.py
Labels: maintenance

#3652 Fix the old import indexDefinition -> index_definition
  docs/examples/search_json_examples.ipynb
Labels: maintenance

#3645 Remove mandatory update the CHANGES file for new PRs. CHANGES file will be kept for history for versions < 4.0.0
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGES
Labels: maintenance

#3655 fix: Revert wrongly changed default value for check_hostname when instantiating RedisSSLContext
  redis/asyncio/connection.py
Labels: bug, async

#3654 fix: Fixed potential deadlock from unexpected __del__ call
  redis/client.py
  redis/cluster.py
  redis/connection.py
Labels: bug, cluster

#3661 maintenance: Update redis-entraid dependency
  dev_requirements.txt
Labels: maintenance

#3653 fix: avoid instantiating a connection on _repr__
  redis/asyncio/connection.py
  redis/connection.py
  tests/test_asyncio/test_connection_pool.py
  tests/test_connection_pool.py
Labels: maintenance
