Repository redis/redis-py, pull requests merged in 2025-01, with the labels that each got.

#3467 Changed default dialect to 2
  redis/commands/search/aggregation.py
  redis/commands/search/dialect.py
  redis/commands/search/query.py
  tests/test_asyncio/test_search.py
  tests/test_auth/test_token_manager.py
  tests/test_search.py
Labels: breakingchange

#3475 Moved ClusterParser exceptions to BaseParser class
  docs/clustering.rst
  redis/_parsers/base.py
  redis/asyncio/cluster.py
  redis/cluster.py
Labels: breakingchange

#3407 DOC-4345 added testable JSON search examples for home page
  doctests/home_json.py
Labels: docs-review

#3469 Added Redis 8.0 to test matrix
  .github/workflows/integration.yaml
  doctests/query_agg.py
  doctests/query_combined.py
  doctests/query_em.py
  doctests/query_ft.py
  doctests/query_geo.py
  doctests/query_range.py
  doctests/search_quickstart.py
  doctests/search_vss.py
  redis/commands/helpers.py
  redis/commands/search/commands.py
  redis/commands/search/index_definition.py
  redis/commands/search/profile_information.py
  tests/test_asyncio/test_search.py
  tests/test_commands.py
  tests/test_helpers.py
  tests/test_search.py
Labels: breakingchange

#3484 Updated test infrastructure with latest versions
  .github/actions/run-tests/action.yml
  .github/workflows/integration.yaml
  redis/commands/search/query.py
  tests/test_asyncio/test_search.py
  tests/test_commands.py
  tests/test_search.py
Labels: maintenance

#3489 Adding tests for modules ACL and modules config changes in 8.0
  redis/commands/search/commands.py
  tests/test_asyncio/test_commands.py
  tests/test_commands.py
Labels: maintenance
