Repository redis/redis-py, pull requests merged in 2025-04, with the labels that each got.

#3585 Run GH pipeline tests against latest 8.0 RC1 image.
  .github/workflows/integration.yaml
Labels: maintenance

#3584 Adding VectorSet commands support.
  docker-compose.yml
  redis/commands/redismodules.py
  redis/commands/vectorset/__init__.py
  redis/commands/vectorset/commands.py
  redis/commands/vectorset/utils.py
  tests/test_asyncio/test_vsets.py
  tests/test_vsets.py
Labels: feature, experimental

#3590 DOC-5073 added examples for vector sets intro page
  doctests/dt_vec_set.py
Labels: docs-review

#3597 DOC-5073 vector set quantization and dimension reduction examples
  doctests/dt_vec_set.py
Labels: docs-review

#3608 Removing 'charset' and 'errors' inputs from the Redis initialization arguments - deprecated 3 years ago.
  docs/advanced_features.rst
  redis/client.py
  redis/cluster.py
Labels: breakingchange

#3609 DOC-5107 added hash examples for index/query intro page
  doctests/home_json.py
  doctests/query_agg.py
  doctests/query_combined.py
  doctests/query_em.py
  doctests/query_ft.py
  doctests/query_geo.py
  doctests/query_range.py
  doctests/search_quickstart.py
  doctests/search_vss.py
Labels: docs-review

#3606 Marks old RediSearch 1.0 commands as deprecated
  redis/commands/search/commands.py
Labels: deprecation

#3586 Handling some special values when transforming response data into list(issue #3573)
  redis/commands/helpers.py
  tests/test_asyncio/test_bloom.py
  tests/test_bloom.py
Labels: bug

#3621 When SlotNotCoveredError is raised, the cluster topology should be reinitialized as part of error handling and retrying of the commands.
  redis/asyncio/cluster.py
  redis/cluster.py
Labels: bug

#3625 Fixing the versions of some deprecations that wrongly added as 5.0.3 - the correct version is 5.3.0
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/cluster.py
  redis/connection.py
Labels: maintenance

#3623 Updating pipeline tests to use test libs image with RC2. Updating timeseries tests.
  .github/workflows/integration.yaml
  docker-compose.yml
  tests/test_asyncio/test_timeseries.py
  tests/test_timeseries.py
Labels: maintenance

#3434 Updated default value of 'require_full_coverage' argument to true for sync Cluster client to match sync/async cluster APIs
  redis/cluster.py
Labels: breakingchange

#3626 Changing the default value for ssl_check_hostname to True, to ensure security validations are not skipped by default
  docs/examples/ssl_connection_examples.ipynb
  redis/asyncio/client.py
  redis/asyncio/cluster.py
  redis/asyncio/connection.py
  redis/client.py
  redis/connection.py
  tests/test_asyncio/test_cluster.py
  tests/test_asyncio/test_connect.py
  tests/test_connect.py
  tests/test_ssl.py
Labels: breakingchange
